// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uagd/ugov/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	types "uagd/x/fund/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreatePlan creates a new draft plan.
type MsgCreatePlan struct {
	Creator     string         `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	FundAddress string         `protobuf:"bytes,2,opt,name=fund_address,json=fundAddress,proto3" json:"fund_address,omitempty"`
	Title       string         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Plan        types.FundPlan `protobuf:"bytes,5,opt,name=plan,proto3" json:"plan"`
}

func (m *MsgCreatePlan) Reset()         { *m = MsgCreatePlan{} }
func (m *MsgCreatePlan) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlan) ProtoMessage()    {}
func (*MsgCreatePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{0}
}
func (m *MsgCreatePlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlan.Merge(m, src)
}
func (m *MsgCreatePlan) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlan proto.InternalMessageInfo

func (m *MsgCreatePlan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePlan) GetFundAddress() string {
	if m != nil {
		return m.FundAddress
	}
	return ""
}

func (m *MsgCreatePlan) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgCreatePlan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgCreatePlan) GetPlan() types.FundPlan {
	if m != nil {
		return m.Plan
	}
	return types.FundPlan{}
}

type MsgCreatePlanResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreatePlanResponse) Reset()         { *m = MsgCreatePlanResponse{} }
func (m *MsgCreatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlanResponse) ProtoMessage()    {}
func (*MsgCreatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{1}
}
func (m *MsgCreatePlanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlanResponse.Merge(m, src)
}
func (m *MsgCreatePlanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlanResponse proto.InternalMessageInfo

func (m *MsgCreatePlanResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// MsgUpdatePlan updates an existing draft plan.
type MsgUpdatePlan struct {
	Creator     string         `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id          uint64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Title       string         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Plan        types.FundPlan `protobuf:"bytes,5,opt,name=plan,proto3" json:"plan"`
}

func (m *MsgUpdatePlan) Reset()         { *m = MsgUpdatePlan{} }
func (m *MsgUpdatePlan) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePlan) ProtoMessage()    {}
func (*MsgUpdatePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{2}
}
func (m *MsgUpdatePlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePlan.Merge(m, src)
}
func (m *MsgUpdatePlan) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePlan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePlan proto.InternalMessageInfo

func (m *MsgUpdatePlan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdatePlan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdatePlan) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUpdatePlan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgUpdatePlan) GetPlan() types.FundPlan {
	if m != nil {
		return m.Plan
	}
	return types.FundPlan{}
}

type MsgUpdatePlanResponse struct {
}

func (m *MsgUpdatePlanResponse) Reset()         { *m = MsgUpdatePlanResponse{} }
func (m *MsgUpdatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePlanResponse) ProtoMessage()    {}
func (*MsgUpdatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{3}
}
func (m *MsgUpdatePlanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePlanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePlanResponse.Merge(m, src)
}
func (m *MsgUpdatePlanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePlanResponse proto.InternalMessageInfo

// MsgSubmitPlan marks a plan as submitted and stores the proposal id if provided.
type MsgSubmitPlan struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id         uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ProposalId uint64 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *MsgSubmitPlan) Reset()         { *m = MsgSubmitPlan{} }
func (m *MsgSubmitPlan) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPlan) ProtoMessage()    {}
func (*MsgSubmitPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{4}
}
func (m *MsgSubmitPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPlan.Merge(m, src)
}
func (m *MsgSubmitPlan) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPlan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPlan proto.InternalMessageInfo

func (m *MsgSubmitPlan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitPlan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgSubmitPlan) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

type MsgSubmitPlanResponse struct {
}

func (m *MsgSubmitPlanResponse) Reset()         { *m = MsgSubmitPlanResponse{} }
func (m *MsgSubmitPlanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPlanResponse) ProtoMessage()    {}
func (*MsgSubmitPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{5}
}
func (m *MsgSubmitPlanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPlanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPlanResponse.Merge(m, src)
}
func (m *MsgSubmitPlanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPlanResponse proto.InternalMessageInfo

// MsgExecuteFundPlan is executed by x/gov authority (via proposal message execution).
type MsgExecuteFundPlan struct {
	// authority is expected to be the x/gov module account address (or configured ugov authority).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// plan_id references a stored ugov plan.
	PlanId uint64 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
}

func (m *MsgExecuteFundPlan) Reset()         { *m = MsgExecuteFundPlan{} }
func (m *MsgExecuteFundPlan) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteFundPlan) ProtoMessage()    {}
func (*MsgExecuteFundPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{6}
}
func (m *MsgExecuteFundPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteFundPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteFundPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteFundPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteFundPlan.Merge(m, src)
}
func (m *MsgExecuteFundPlan) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteFundPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteFundPlan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteFundPlan proto.InternalMessageInfo

func (m *MsgExecuteFundPlan) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgExecuteFundPlan) GetPlanId() uint64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

type MsgExecuteFundPlanResponse struct {
}

func (m *MsgExecuteFundPlanResponse) Reset()         { *m = MsgExecuteFundPlanResponse{} }
func (m *MsgExecuteFundPlanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteFundPlanResponse) ProtoMessage()    {}
func (*MsgExecuteFundPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba276dfac56d22bb, []int{7}
}
func (m *MsgExecuteFundPlanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteFundPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteFundPlanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteFundPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteFundPlanResponse.Merge(m, src)
}
func (m *MsgExecuteFundPlanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteFundPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteFundPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteFundPlanResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreatePlan)(nil), "uagd.ugov.v1.MsgCreatePlan")
	proto.RegisterType((*MsgCreatePlanResponse)(nil), "uagd.ugov.v1.MsgCreatePlanResponse")
	proto.RegisterType((*MsgUpdatePlan)(nil), "uagd.ugov.v1.MsgUpdatePlan")
	proto.RegisterType((*MsgUpdatePlanResponse)(nil), "uagd.ugov.v1.MsgUpdatePlanResponse")
	proto.RegisterType((*MsgSubmitPlan)(nil), "uagd.ugov.v1.MsgSubmitPlan")
	proto.RegisterType((*MsgSubmitPlanResponse)(nil), "uagd.ugov.v1.MsgSubmitPlanResponse")
	proto.RegisterType((*MsgExecuteFundPlan)(nil), "uagd.ugov.v1.MsgExecuteFundPlan")
	proto.RegisterType((*MsgExecuteFundPlanResponse)(nil), "uagd.ugov.v1.MsgExecuteFundPlanResponse")
}

func init() { proto.RegisterFile("uagd/ugov/v1/tx.proto", fileDescriptor_ba276dfac56d22bb) }

var fileDescriptor_ba276dfac56d22bb = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xdd, 0xa4, 0x55, 0x5f, 0x0a, 0xa8, 0xa7, 0x94, 0xb8, 0x06, 0xb9, 0x91, 0x19, 0x88,
	0x82, 0xb0, 0x49, 0x90, 0x18, 0xca, 0x44, 0x10, 0x48, 0x1d, 0x52, 0x21, 0x57, 0x2c, 0x48, 0x28,
	0x72, 0x73, 0xc6, 0x58, 0x4a, 0x7c, 0x96, 0xef, 0x1c, 0xa5, 0x1b, 0x62, 0x64, 0x62, 0x42, 0x8c,
	0xfc, 0x84, 0x0c, 0xfc, 0x88, 0x8e, 0x15, 0x13, 0x12, 0x12, 0x42, 0xc9, 0x10, 0xf1, 0x2f, 0xd0,
	0x9d, 0xe3, 0xd8, 0x89, 0x2b, 0x32, 0xc0, 0xd0, 0x25, 0xc9, 0xfb, 0xbe, 0x77, 0x5f, 0xbe, 0xf7,
	0xdd, 0xb3, 0x61, 0x2f, 0xb2, 0x5d, 0x6c, 0x46, 0x2e, 0x19, 0x9a, 0xc3, 0xa6, 0xc9, 0x46, 0x46,
	0x10, 0x12, 0x46, 0xd0, 0x0e, 0x87, 0x0d, 0x0e, 0x1b, 0xc3, 0xa6, 0xba, 0x6b, 0x0f, 0x3c, 0x9f,
	0x98, 0xe2, 0x33, 0x6e, 0x50, 0xab, 0x3d, 0x42, 0x07, 0x84, 0x9a, 0x03, 0xea, 0xf2, 0x83, 0x03,
	0xea, 0xce, 0x89, 0xfd, 0x98, 0xe8, 0x8a, 0xca, 0x8c, 0x8b, 0x39, 0x55, 0x71, 0x89, 0x4b, 0x62,
	0x9c, 0xff, 0x4a, 0x94, 0x84, 0x83, 0x37, 0x91, 0x8f, 0xb9, 0x10, 0xff, 0x8e, 0x09, 0xfd, 0x93,
	0x0c, 0xd7, 0x3a, 0xd4, 0x7d, 0x1a, 0x3a, 0x36, 0x73, 0x5e, 0xf4, 0x6d, 0x1f, 0xb5, 0x60, 0xab,
	0xc7, 0x2b, 0x12, 0x2a, 0x52, 0x4d, 0xaa, 0x6f, 0xb7, 0x95, 0x6f, 0x5f, 0xef, 0x57, 0xe6, 0xff,
	0xf1, 0x04, 0xe3, 0xd0, 0xa1, 0xf4, 0x84, 0x85, 0x9e, 0xef, 0x5a, 0x49, 0x23, 0x7a, 0x0c, 0x3b,
	0x5c, 0xb3, 0x6b, 0xc7, 0xb4, 0x22, 0xaf, 0x39, 0x58, 0xe6, 0xdd, 0x73, 0x08, 0x55, 0xa0, 0xc4,
	0x3c, 0xd6, 0x77, 0x94, 0x0d, 0x7e, 0xca, 0x8a, 0x0b, 0x54, 0x83, 0x32, 0x76, 0x68, 0x2f, 0xf4,
	0x02, 0xe6, 0x11, 0x5f, 0x29, 0x0a, 0x2e, 0x0b, 0xa1, 0x07, 0x50, 0x0c, 0xfa, 0xb6, 0xaf, 0x94,
	0x6a, 0x52, 0xbd, 0xdc, 0xba, 0x69, 0x88, 0x34, 0xc5, 0x68, 0xc3, 0xa6, 0xf1, 0x3c, 0xf2, 0x31,
	0x1f, 0xa7, 0x5d, 0x3c, 0xff, 0x79, 0x50, 0xb0, 0x44, 0xe7, 0x61, 0xe3, 0xfd, 0x6c, 0xdc, 0x48,
	0x4c, 0x7f, 0x98, 0x8d, 0x1b, 0xfb, 0x22, 0x96, 0x51, 0x7c, 0x35, 0x4b, 0x31, 0xe8, 0x77, 0x61,
	0x6f, 0x09, 0xb0, 0x1c, 0x1a, 0x10, 0x9f, 0x3a, 0xe8, 0x3a, 0xc8, 0x1e, 0x16, 0xd1, 0x14, 0x2d,
	0xd9, 0xc3, 0xfa, 0x6f, 0x49, 0x24, 0xf8, 0x32, 0xc0, 0xff, 0x92, 0x60, 0xac, 0x2a, 0x27, 0xaa,
	0x57, 0x29, 0x94, 0x74, 0x32, 0xbd, 0x2a, 0x42, 0x49, 0x81, 0x24, 0x14, 0xfd, 0x4b, 0x1c, 0xc2,
	0x49, 0x74, 0x3a, 0xf0, 0xd8, 0x7f, 0x0b, 0xe1, 0x00, 0xca, 0x41, 0x48, 0x02, 0x42, 0xed, 0x7e,
	0xd7, 0xc3, 0x22, 0x8a, 0xa2, 0x05, 0x09, 0x74, 0x84, 0xd7, 0x7b, 0x4f, 0x0d, 0xcd, 0xbd, 0xa7,
	0xc0, 0xc2, 0xfb, 0x67, 0x09, 0x50, 0x87, 0xba, 0xcf, 0x46, 0x4e, 0x2f, 0x62, 0x4e, 0x92, 0x11,
	0x7a, 0x04, 0xdb, 0x76, 0xc4, 0xde, 0x92, 0xd0, 0x63, 0x67, 0x6b, 0x47, 0x48, 0x5b, 0x51, 0x15,
	0xb6, 0x78, 0xae, 0xdd, 0xc5, 0x24, 0x9b, 0xbc, 0x3c, 0xc2, 0x87, 0x4d, 0x6e, 0x36, 0x6d, 0xe4,
	0x76, 0xb5, 0x15, 0xbb, 0x2b, 0x1e, 0xf4, 0xdb, 0xa0, 0xe6, 0xd1, 0xc4, 0x78, 0xeb, 0x87, 0x0c,
	0x1b, 0x1d, 0xea, 0xa2, 0x63, 0x80, 0xcc, 0xf3, 0x7b, 0xcb, 0xc8, 0xbe, 0x56, 0x8c, 0xa5, 0x25,
	0x56, 0xef, 0xfc, 0x85, 0x5c, 0x6c, 0xf8, 0x31, 0x40, 0x66, 0x9b, 0xf3, 0x7a, 0x29, 0x79, 0x89,
	0x5e, 0x7e, 0x39, 0xb8, 0x5e, 0x66, 0x31, 0xf2, 0x7a, 0x29, 0x79, 0x89, 0x5e, 0xfe, 0xc2, 0xd0,
	0x6b, 0xb8, 0xb1, 0x7a, 0x59, 0xb5, 0xdc, 0xb9, 0x95, 0x0e, 0xb5, 0xbe, 0xae, 0x23, 0x91, 0x57,
	0x4b, 0xef, 0x66, 0xe3, 0x86, 0xd4, 0xbe, 0x77, 0x3e, 0xd1, 0xa4, 0x8b, 0x89, 0x26, 0xfd, 0x9a,
	0x68, 0xd2, 0xc7, 0xa9, 0x56, 0xb8, 0x98, 0x6a, 0x85, 0xef, 0x53, 0xad, 0xf0, 0x6a, 0x37, 0x7b,
	0x6b, 0xec, 0x2c, 0x70, 0xe8, 0xe9, 0xa6, 0x78, 0x9b, 0x3e, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xb8, 0x86, 0x7d, 0xef, 0xea, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreatePlan creates a DRAFT plan (president flow).
	CreatePlan(ctx context.Context, in *MsgCreatePlan, opts ...grpc.CallOption) (*MsgCreatePlanResponse, error)
	// UpdatePlan updates a DRAFT plan fields.
	UpdatePlan(ctx context.Context, in *MsgUpdatePlan, opts ...grpc.CallOption) (*MsgUpdatePlanResponse, error)
	// SubmitPlan marks a plan as SUBMITTED (typically after creating a gov proposal off-chain).
	SubmitPlan(ctx context.Context, in *MsgSubmitPlan, opts ...grpc.CallOption) (*MsgSubmitPlanResponse, error)
	// ExecuteFundPlan is the governance-executed message: included inside a x/gov v1 proposal.
	ExecuteFundPlan(ctx context.Context, in *MsgExecuteFundPlan, opts ...grpc.CallOption) (*MsgExecuteFundPlanResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePlan(ctx context.Context, in *MsgCreatePlan, opts ...grpc.CallOption) (*MsgCreatePlanResponse, error) {
	out := new(MsgCreatePlanResponse)
	err := c.cc.Invoke(ctx, "/uagd.ugov.v1.Msg/CreatePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePlan(ctx context.Context, in *MsgUpdatePlan, opts ...grpc.CallOption) (*MsgUpdatePlanResponse, error) {
	out := new(MsgUpdatePlanResponse)
	err := c.cc.Invoke(ctx, "/uagd.ugov.v1.Msg/UpdatePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitPlan(ctx context.Context, in *MsgSubmitPlan, opts ...grpc.CallOption) (*MsgSubmitPlanResponse, error) {
	out := new(MsgSubmitPlanResponse)
	err := c.cc.Invoke(ctx, "/uagd.ugov.v1.Msg/SubmitPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteFundPlan(ctx context.Context, in *MsgExecuteFundPlan, opts ...grpc.CallOption) (*MsgExecuteFundPlanResponse, error) {
	out := new(MsgExecuteFundPlanResponse)
	err := c.cc.Invoke(ctx, "/uagd.ugov.v1.Msg/ExecuteFundPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreatePlan creates a DRAFT plan (president flow).
	CreatePlan(context.Context, *MsgCreatePlan) (*MsgCreatePlanResponse, error)
	// UpdatePlan updates a DRAFT plan fields.
	UpdatePlan(context.Context, *MsgUpdatePlan) (*MsgUpdatePlanResponse, error)
	// SubmitPlan marks a plan as SUBMITTED (typically after creating a gov proposal off-chain).
	SubmitPlan(context.Context, *MsgSubmitPlan) (*MsgSubmitPlanResponse, error)
	// ExecuteFundPlan is the governance-executed message: included inside a x/gov v1 proposal.
	ExecuteFundPlan(context.Context, *MsgExecuteFundPlan) (*MsgExecuteFundPlanResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePlan(ctx context.Context, req *MsgCreatePlan) (*MsgCreatePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlan not implemented")
}
func (*UnimplementedMsgServer) UpdatePlan(ctx context.Context, req *MsgUpdatePlan) (*MsgUpdatePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (*UnimplementedMsgServer) SubmitPlan(ctx context.Context, req *MsgSubmitPlan) (*MsgSubmitPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPlan not implemented")
}
func (*UnimplementedMsgServer) ExecuteFundPlan(ctx context.Context, req *MsgExecuteFundPlan) (*MsgExecuteFundPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFundPlan not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uagd.ugov.v1.Msg/CreatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePlan(ctx, req.(*MsgCreatePlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uagd.ugov.v1.Msg/UpdatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePlan(ctx, req.(*MsgUpdatePlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uagd.ugov.v1.Msg/SubmitPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPlan(ctx, req.(*MsgSubmitPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteFundPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteFundPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteFundPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uagd.ugov.v1.Msg/ExecuteFundPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteFundPlan(ctx, req.(*MsgExecuteFundPlan))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uagd.ugov.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _Msg_CreatePlan_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _Msg_UpdatePlan_Handler,
		},
		{
			MethodName: "SubmitPlan",
			Handler:    _Msg_SubmitPlan_Handler,
		},
		{
			MethodName: "ExecuteFundPlan",
			Handler:    _Msg_ExecuteFundPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uagd/ugov/v1/tx.proto",
}

func (m *MsgCreatePlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FundAddress) > 0 {
		i -= len(m.FundAddress)
		copy(dAtA[i:], m.FundAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FundAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePlanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePlanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePlanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePlanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPlanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPlanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPlanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExecuteFundPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteFundPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteFundPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PlanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PlanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteFundPlanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteFundPlanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteFundPlanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FundAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Plan.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreatePlanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdatePlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Plan.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdatePlanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.ProposalId != 0 {
		n += 1 + sovTx(uint64(m.ProposalId))
	}
	return n
}

func (m *MsgSubmitPlanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExecuteFundPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PlanId != 0 {
		n += 1 + sovTx(uint64(m.PlanId))
	}
	return n
}

func (m *MsgExecuteFundPlanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePlanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePlanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePlanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePlanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPlanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPlanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPlanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteFundPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteFundPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteFundPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanId", wireType)
			}
			m.PlanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteFundPlanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteFundPlanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteFundPlanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
