// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uagd/fund/v1/fund.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FundType enumerates protocol-owned fund categories.
type FundType int32

const (
	FundType_FUND_TYPE_REGION   FundType = 0
	FundType_FUND_TYPE_UKRAINE  FundType = 1
	FundType_FUND_TYPE_PROJECTS FundType = 2
)

var FundType_name = map[int32]string{
	0: "FUND_TYPE_REGION",
	1: "FUND_TYPE_UKRAINE",
	2: "FUND_TYPE_PROJECTS",
}

var FundType_value = map[string]int32{
	"FUND_TYPE_REGION":   0,
	"FUND_TYPE_UKRAINE":  1,
	"FUND_TYPE_PROJECTS": 2,
}

func (x FundType) String() string {
	return proto.EnumName(FundType_name, int32(x))
}

func (FundType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e1dd3542aee5bed, []int{0}
}

// Fund models a protocol-owned wallet with configuration metadata.
type Fund struct {
	Address             string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type                FundType   `protobuf:"varint,2,opt,name=type,proto3,enum=uagd.fund.v1.FundType" json:"type,omitempty"`
	RegionId            string     `protobuf:"bytes,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Name                string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description         string     `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	President           string     `protobuf:"bytes,6,opt,name=president,proto3" json:"president,omitempty"`
	BaseDelegationLimit types.Coin `protobuf:"bytes,7,opt,name=base_delegation_limit,json=baseDelegationLimit,proto3" json:"base_delegation_limit"`
	BasePayrollLimit    types.Coin `protobuf:"bytes,8,opt,name=base_payroll_limit,json=basePayrollLimit,proto3" json:"base_payroll_limit"`
	Active              bool       `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *Fund) Reset()         { *m = Fund{} }
func (m *Fund) String() string { return proto.CompactTextString(m) }
func (*Fund) ProtoMessage()    {}
func (*Fund) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1dd3542aee5bed, []int{0}
}
func (m *Fund) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fund.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fund.Merge(m, src)
}
func (m *Fund) XXX_Size() int {
	return m.Size()
}
func (m *Fund) XXX_DiscardUnknown() {
	xxx_messageInfo_Fund.DiscardUnknown(m)
}

var xxx_messageInfo_Fund proto.InternalMessageInfo

func (m *Fund) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Fund) GetType() FundType {
	if m != nil {
		return m.Type
	}
	return FundType_FUND_TYPE_REGION
}

func (m *Fund) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *Fund) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fund) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Fund) GetPresident() string {
	if m != nil {
		return m.President
	}
	return ""
}

func (m *Fund) GetBaseDelegationLimit() types.Coin {
	if m != nil {
		return m.BaseDelegationLimit
	}
	return types.Coin{}
}

func (m *Fund) GetBasePayrollLimit() types.Coin {
	if m != nil {
		return m.BasePayrollLimit
	}
	return types.Coin{}
}

func (m *Fund) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// FundDelegation represents one delegation action to a validator.
type FundDelegation struct {
	ValidatorAddress string     `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Amount           types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *FundDelegation) Reset()         { *m = FundDelegation{} }
func (m *FundDelegation) String() string { return proto.CompactTextString(m) }
func (*FundDelegation) ProtoMessage()    {}
func (*FundDelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1dd3542aee5bed, []int{1}
}
func (m *FundDelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FundDelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FundDelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FundDelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundDelegation.Merge(m, src)
}
func (m *FundDelegation) XXX_Size() int {
	return m.Size()
}
func (m *FundDelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_FundDelegation.DiscardUnknown(m)
}

var xxx_messageInfo_FundDelegation proto.InternalMessageInfo

func (m *FundDelegation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *FundDelegation) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// FundPayout represents one payment to a recipient.
type FundPayout struct {
	RecipientAddress string     `protobuf:"bytes,1,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	Amount           types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	Category         string     `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (m *FundPayout) Reset()         { *m = FundPayout{} }
func (m *FundPayout) String() string { return proto.CompactTextString(m) }
func (*FundPayout) ProtoMessage()    {}
func (*FundPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1dd3542aee5bed, []int{2}
}
func (m *FundPayout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FundPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FundPayout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FundPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundPayout.Merge(m, src)
}
func (m *FundPayout) XXX_Size() int {
	return m.Size()
}
func (m *FundPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_FundPayout.DiscardUnknown(m)
}

var xxx_messageInfo_FundPayout proto.InternalMessageInfo

func (m *FundPayout) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *FundPayout) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *FundPayout) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// FundPosition captures a set of delegations and payouts to execute for a fund.
type FundPosition struct {
	Id          uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FundAddress string           `protobuf:"bytes,2,opt,name=fund_address,json=fundAddress,proto3" json:"fund_address,omitempty"`
	Title       string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Delegations []FundDelegation `protobuf:"bytes,5,rep,name=delegations,proto3" json:"delegations"`
	Payouts     []FundPayout     `protobuf:"bytes,6,rep,name=payouts,proto3" json:"payouts"`
}

func (m *FundPosition) Reset()         { *m = FundPosition{} }
func (m *FundPosition) String() string { return proto.CompactTextString(m) }
func (*FundPosition) ProtoMessage()    {}
func (*FundPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1dd3542aee5bed, []int{3}
}
func (m *FundPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FundPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FundPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FundPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundPosition.Merge(m, src)
}
func (m *FundPosition) XXX_Size() int {
	return m.Size()
}
func (m *FundPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_FundPosition.DiscardUnknown(m)
}

var xxx_messageInfo_FundPosition proto.InternalMessageInfo

func (m *FundPosition) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FundPosition) GetFundAddress() string {
	if m != nil {
		return m.FundAddress
	}
	return ""
}

func (m *FundPosition) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FundPosition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FundPosition) GetDelegations() []FundDelegation {
	if m != nil {
		return m.Delegations
	}
	return nil
}

func (m *FundPosition) GetPayouts() []FundPayout {
	if m != nil {
		return m.Payouts
	}
	return nil
}

func init() {
	proto.RegisterEnum("uagd.fund.v1.FundType", FundType_name, FundType_value)
	proto.RegisterType((*Fund)(nil), "uagd.fund.v1.Fund")
	proto.RegisterType((*FundDelegation)(nil), "uagd.fund.v1.FundDelegation")
	proto.RegisterType((*FundPayout)(nil), "uagd.fund.v1.FundPayout")
	proto.RegisterType((*FundPosition)(nil), "uagd.fund.v1.FundPosition")
}

func init() { proto.RegisterFile("uagd/fund/v1/fund.proto", fileDescriptor_3e1dd3542aee5bed) }

var fileDescriptor_3e1dd3542aee5bed = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x53, 0x37, 0x4d, 0x6e, 0xaa, 0xca, 0x99, 0x2f, 0xed, 0xe7, 0x16, 0x30, 0x21, 0xab,
	0xa8, 0xa8, 0x8e, 0x12, 0x24, 0x40, 0x62, 0xd5, 0x9f, 0x14, 0x95, 0x9f, 0x34, 0x72, 0x5b, 0x24,
	0xd8, 0x58, 0xd3, 0xcc, 0x60, 0x8d, 0x94, 0x78, 0x2c, 0x7b, 0x12, 0x91, 0xb7, 0x40, 0x62, 0xc5,
	0x1b, 0xb0, 0x61, 0xd7, 0x87, 0xe8, 0xb2, 0xea, 0x8a, 0x15, 0x42, 0xed, 0x8b, 0xa0, 0x99, 0xb1,
	0x9b, 0xfe, 0x2c, 0x1a, 0x89, 0x55, 0x7c, 0xcf, 0x3d, 0xf7, 0xcc, 0xc9, 0xbd, 0x77, 0x06, 0xfe,
	0x1f, 0xe1, 0x80, 0x34, 0x3f, 0x8f, 0x42, 0xd2, 0x1c, 0xb7, 0xd4, 0xaf, 0x1b, 0xc5, 0x5c, 0x70,
	0xb4, 0x28, 0x13, 0xae, 0x02, 0xc6, 0xad, 0x35, 0xa7, 0xcf, 0x93, 0x21, 0x4f, 0x9a, 0xc7, 0x38,
	0xa1, 0xcd, 0x71, 0xeb, 0x98, 0x0a, 0xdc, 0x6a, 0xf6, 0x39, 0x0b, 0x35, 0x7b, 0x6d, 0x55, 0xe7,
	0x7d, 0x15, 0x35, 0x75, 0x90, 0xa6, 0xaa, 0x01, 0x0f, 0xb8, 0xc6, 0xe5, 0x97, 0x46, 0xeb, 0x3f,
	0xe7, 0xc0, 0xdc, 0x1d, 0x85, 0x04, 0xb5, 0x61, 0x01, 0x13, 0x12, 0xd3, 0x24, 0xb1, 0x8d, 0x9a,
	0xd1, 0x28, 0x6d, 0xd9, 0xe7, 0x27, 0x1b, 0xd5, 0x54, 0x61, 0x53, 0x67, 0x0e, 0x44, 0xcc, 0xc2,
	0xc0, 0xcb, 0x88, 0x68, 0x1d, 0x4c, 0x31, 0x89, 0xa8, 0x9d, 0xaf, 0x19, 0x8d, 0xa5, 0xf6, 0x8a,
	0x7b, 0xdd, 0xaa, 0x2b, 0x55, 0x0f, 0x27, 0x11, 0xf5, 0x14, 0x07, 0x3d, 0x80, 0x52, 0x4c, 0x03,
	0xc6, 0x43, 0x9f, 0x11, 0x7b, 0x4e, 0x9e, 0xe0, 0x15, 0x35, 0xb0, 0x47, 0x10, 0x02, 0x33, 0xc4,
	0x43, 0x6a, 0x9b, 0x0a, 0x57, 0xdf, 0xa8, 0x06, 0x65, 0x42, 0x93, 0x7e, 0xcc, 0x22, 0xc1, 0x78,
	0x68, 0xcf, 0xab, 0xd4, 0x75, 0x08, 0x3d, 0x87, 0x52, 0x14, 0xd3, 0x84, 0x11, 0x1a, 0x0a, 0xbb,
	0x70, 0x8f, 0xe9, 0x29, 0x15, 0x1d, 0xc0, 0xb2, 0xec, 0x9f, 0x4f, 0xe8, 0x80, 0x06, 0x58, 0x4a,
	0xf9, 0x03, 0x36, 0x64, 0xc2, 0x5e, 0xa8, 0x19, 0x8d, 0x72, 0x7b, 0xd5, 0x4d, 0x05, 0x24, 0xc9,
	0x4d, 0x9b, 0xec, 0x6e, 0x73, 0x16, 0x6e, 0x99, 0xa7, 0xbf, 0x1f, 0xe7, 0xbc, 0xff, 0x64, 0x62,
	0xe7, 0xaa, 0xf8, 0x9d, 0xac, 0x45, 0xef, 0x01, 0x29, 0xd1, 0x08, 0x4f, 0x62, 0x3e, 0x18, 0xa4,
	0x8a, 0xc5, 0xd9, 0x14, 0x2d, 0x99, 0xe8, 0xe9, 0x4a, 0x2d, 0xb7, 0x02, 0x05, 0xdc, 0x17, 0x6c,
	0x4c, 0xed, 0x52, 0xcd, 0x68, 0x14, 0xbd, 0x34, 0xaa, 0x7f, 0x37, 0x60, 0x49, 0x76, 0x76, 0x7a,
	0x3c, 0xea, 0x42, 0x65, 0x8c, 0x07, 0x8c, 0x60, 0xc1, 0x63, 0xff, 0xe6, 0x0c, 0x9f, 0x9c, 0x9f,
	0x6c, 0x3c, 0x4a, 0xcf, 0xfe, 0x90, 0x71, 0x6e, 0xf6, 0xc5, 0x1a, 0xdf, 0xc2, 0xd1, 0x0b, 0x28,
	0xe0, 0x21, 0x1f, 0x85, 0x42, 0xcd, 0x75, 0x06, 0xf7, 0x29, 0xbd, 0xfe, 0xc3, 0x00, 0x90, 0xde,
	0x7a, 0x78, 0xc2, 0x47, 0x02, 0x75, 0xa0, 0x12, 0xd3, 0x3e, 0x8b, 0x18, 0x0d, 0x85, 0x3f, 0xeb,
	0x6e, 0x59, 0x57, 0x25, 0xff, 0x6a, 0x07, 0xad, 0x41, 0xb1, 0x8f, 0x05, 0x0d, 0x78, 0x3c, 0xc9,
	0x16, 0x2e, 0x8b, 0xeb, 0xdf, 0xf2, 0xb0, 0xa8, 0xac, 0xf2, 0x84, 0xa9, 0x26, 0x2e, 0x41, 0x9e,
	0x11, 0xe5, 0xce, 0xf4, 0xf2, 0x8c, 0xa0, 0x57, 0xb0, 0x28, 0x17, 0xf9, 0xca, 0x77, 0xfe, 0x1e,
	0xdf, 0x65, 0xc9, 0xce, 0x2c, 0x57, 0x61, 0x5e, 0x30, 0x31, 0xa0, 0xe9, 0xb1, 0x3a, 0xb8, 0xbd,
	0xd0, 0xe6, 0xdd, 0x85, 0xde, 0x91, 0x8c, 0x6c, 0xae, 0x89, 0x3d, 0x5f, 0x9b, 0x6b, 0x94, 0xdb,
	0x0f, 0xef, 0x5e, 0xab, 0xe9, 0xf0, 0xd3, 0xbf, 0x7c, 0xbd, 0x0c, 0xbd, 0x84, 0x85, 0x48, 0x4d,
	0x20, 0xb1, 0x0b, 0x4a, 0xc1, 0xbe, 0xab, 0xa0, 0x47, 0x94, 0x56, 0x67, 0xf4, 0xf5, 0x7d, 0x28,
	0x66, 0xb7, 0x16, 0x55, 0xc1, 0xda, 0x3d, 0xea, 0xee, 0xf8, 0x87, 0x1f, 0x7b, 0x1d, 0xdf, 0xeb,
	0xbc, 0xde, 0xdb, 0xef, 0x5a, 0x39, 0xb4, 0x0c, 0x95, 0x29, 0x7a, 0xf4, 0xd6, 0xdb, 0xdc, 0xeb,
	0x76, 0x2c, 0x03, 0xad, 0x00, 0x9a, 0xc2, 0x3d, 0x6f, 0xff, 0x4d, 0x67, 0xfb, 0xf0, 0xc0, 0xca,
	0x6f, 0x3d, 0x3d, 0xbd, 0x70, 0x8c, 0xb3, 0x0b, 0xc7, 0xf8, 0x73, 0xe1, 0x18, 0x5f, 0x2f, 0x9d,
	0xdc, 0xd9, 0xa5, 0x93, 0xfb, 0x75, 0xe9, 0xe4, 0x3e, 0x55, 0xd4, 0x7b, 0xf7, 0x45, 0xbf, 0x78,
	0xf2, 0x81, 0x48, 0x8e, 0x0b, 0xea, 0x45, 0x7a, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x44, 0xea,
	0xe9, 0x4f, 0x0b, 0x05, 0x00, 0x00,
}

func (m *Fund) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fund) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fund) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	{
		size, err := m.BasePayrollLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFund(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.BaseDelegationLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFund(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.President) > 0 {
		i -= len(m.President)
		copy(dAtA[i:], m.President)
		i = encodeVarintFund(dAtA, i, uint64(len(m.President)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintFund(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintFund(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FundDelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FundDelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FundDelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFund(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintFund(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FundPayout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FundPayout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FundPayout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFund(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.RecipientAddress) > 0 {
		i -= len(m.RecipientAddress)
		copy(dAtA[i:], m.RecipientAddress)
		i = encodeVarintFund(dAtA, i, uint64(len(m.RecipientAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FundPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FundPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FundPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payouts) > 0 {
		for iNdEx := len(m.Payouts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payouts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFund(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Delegations) > 0 {
		for iNdEx := len(m.Delegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFund(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintFund(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FundAddress) > 0 {
		i -= len(m.FundAddress)
		copy(dAtA[i:], m.FundAddress)
		i = encodeVarintFund(dAtA, i, uint64(len(m.FundAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintFund(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFund(dAtA []byte, offset int, v uint64) int {
	offset -= sovFund(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fund) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovFund(uint64(m.Type))
	}
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = len(m.President)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = m.BaseDelegationLimit.Size()
	n += 1 + l + sovFund(uint64(l))
	l = m.BasePayrollLimit.Size()
	n += 1 + l + sovFund(uint64(l))
	if m.Active {
		n += 2
	}
	return n
}

func (m *FundDelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFund(uint64(l))
	return n
}

func (m *FundPayout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecipientAddress)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFund(uint64(l))
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	return n
}

func (m *FundPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFund(uint64(m.Id))
	}
	l = len(m.FundAddress)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovFund(uint64(l))
	}
	if len(m.Delegations) > 0 {
		for _, e := range m.Delegations {
			l = e.Size()
			n += 1 + l + sovFund(uint64(l))
		}
	}
	if len(m.Payouts) > 0 {
		for _, e := range m.Payouts {
			l = e.Size()
			n += 1 + l + sovFund(uint64(l))
		}
	}
	return n
}

func sovFund(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFund(x uint64) (n int) {
	return sovFund(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Fund) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFund
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fund: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fund: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= FundType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field President", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.President = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDelegationLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseDelegationLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePayrollLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BasePayrollLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFund(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFund
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FundDelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFund
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FundDelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FundDelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFund(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFund
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FundPayout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFund
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FundPayout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FundPayout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFund(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFund
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FundPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFund
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FundPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FundPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegations = append(m.Delegations, FundDelegation{})
			if err := m.Delegations[len(m.Delegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payouts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payouts = append(m.Payouts, FundPayout{})
			if err := m.Payouts[len(m.Payouts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFund(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFund
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFund(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFund
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFund
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFund
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFund
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFund
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFund
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFund        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFund          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFund = fmt.Errorf("proto: unexpected end of group")
)
