// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/fund/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the fund module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Funds         []*Fund                `protobuf:"bytes,2,rep,name=funds,proto3" json:"funds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_uagd_fund_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetFunds() []*Fund {
	if x != nil {
		return x.Funds
	}
	return nil
}

var File_uagd_fund_v1_genesis_proto protoreflect.FileDescriptor

const file_uagd_fund_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"\x1auagd/fund/v1/genesis.proto\x12\fuagd.fund.v1\x1a\x11amino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x17uagd/fund/v1/fund.proto\x1a\x19uagd/fund/v1/params.proto\"\x91\x01\n" +
	"\fGenesisState\x122\n" +
	"\x06params\x18\x01 \x01(\v2\x14.uagd.fund.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12.\n" +
	"\x05funds\x18\x02 \x03(\v2\x12.uagd.fund.v1.FundB\x04\xc8\xde\x1f\x00R\x05funds:\x1d\x8a\xe7\xb0*\x18uagd/x/fund/GenesisStateB\x13Z\x11uagd/x/fund/typesb\x06proto3"

var (
	file_uagd_fund_v1_genesis_proto_rawDescOnce sync.Once
	file_uagd_fund_v1_genesis_proto_rawDescData []byte
)

func file_uagd_fund_v1_genesis_proto_rawDescGZIP() []byte {
	file_uagd_fund_v1_genesis_proto_rawDescOnce.Do(func() {
		file_uagd_fund_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_genesis_proto_rawDesc), len(file_uagd_fund_v1_genesis_proto_rawDesc)))
	})
	return file_uagd_fund_v1_genesis_proto_rawDescData
}

var file_uagd_fund_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uagd_fund_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil), // 0: uagd.fund.v1.GenesisState
	(*Params)(nil),       // 1: uagd.fund.v1.Params
	(*Fund)(nil),         // 2: uagd.fund.v1.Fund
}
var file_uagd_fund_v1_genesis_proto_depIdxs = []int32{
	1, // 0: uagd.fund.v1.GenesisState.params:type_name -> uagd.fund.v1.Params
	2, // 1: uagd.fund.v1.GenesisState.funds:type_name -> uagd.fund.v1.Fund
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_uagd_fund_v1_genesis_proto_init() }
func file_uagd_fund_v1_genesis_proto_init() {
	if File_uagd_fund_v1_genesis_proto != nil {
		return
	}
	file_uagd_fund_v1_fund_proto_init()
	file_uagd_fund_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_genesis_proto_rawDesc), len(file_uagd_fund_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uagd_fund_v1_genesis_proto_goTypes,
		DependencyIndexes: file_uagd_fund_v1_genesis_proto_depIdxs,
		MessageInfos:      file_uagd_fund_v1_genesis_proto_msgTypes,
	}.Build()
	File_uagd_fund_v1_genesis_proto = out.File
	file_uagd_fund_v1_genesis_proto_goTypes = nil
	file_uagd_fund_v1_genesis_proto_depIdxs = nil
}
