// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/fund/v1/params.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the fund module parameters.
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// admin is the address allowed to execute fund plans.
	Admin         string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_uagd_fund_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

var File_uagd_fund_v1_params_proto protoreflect.FileDescriptor

const file_uagd_fund_v1_params_proto_rawDesc = "" +
	"\n" +
	"\x19uagd/fund/v1/params.proto\x12\fuagd.fund.v1\x1a\x11amino/amino.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"Q\n" +
	"\x06Params\x12.\n" +
	"\x05admin\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x05admin:\x17\x8a\xe7\xb0*\x12uagd/x/fund/ParamsB\x13Z\x11uagd/x/fund/typesb\x06proto3"

var (
	file_uagd_fund_v1_params_proto_rawDescOnce sync.Once
	file_uagd_fund_v1_params_proto_rawDescData []byte
)

func file_uagd_fund_v1_params_proto_rawDescGZIP() []byte {
	file_uagd_fund_v1_params_proto_rawDescOnce.Do(func() {
		file_uagd_fund_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_params_proto_rawDesc), len(file_uagd_fund_v1_params_proto_rawDesc)))
	})
	return file_uagd_fund_v1_params_proto_rawDescData
}

var file_uagd_fund_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uagd_fund_v1_params_proto_goTypes = []any{
	(*Params)(nil), // 0: uagd.fund.v1.Params
}
var file_uagd_fund_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uagd_fund_v1_params_proto_init() }
func file_uagd_fund_v1_params_proto_init() {
	if File_uagd_fund_v1_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_params_proto_rawDesc), len(file_uagd_fund_v1_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uagd_fund_v1_params_proto_goTypes,
		DependencyIndexes: file_uagd_fund_v1_params_proto_depIdxs,
		MessageInfos:      file_uagd_fund_v1_params_proto_msgTypes,
	}.Build()
	File_uagd_fund_v1_params_proto = out.File
	file_uagd_fund_v1_params_proto_goTypes = nil
	file_uagd_fund_v1_params_proto_depIdxs = nil
}
