// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/fund/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryFundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundRequest) Reset() {
	*x = QueryFundRequest{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundRequest) ProtoMessage() {}

func (x *QueryFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundRequest.ProtoReflect.Descriptor instead.
func (*QueryFundRequest) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryFundRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryFundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fund          *Fund                  `protobuf:"bytes,1,opt,name=fund,proto3" json:"fund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundResponse) Reset() {
	*x = QueryFundResponse{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundResponse) ProtoMessage() {}

func (x *QueryFundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundResponse.ProtoReflect.Descriptor instead.
func (*QueryFundResponse) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFundResponse) GetFund() *Fund {
	if x != nil {
		return x.Fund
	}
	return nil
}

type QueryFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundsRequest) Reset() {
	*x = QueryFundsRequest{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundsRequest) ProtoMessage() {}

func (x *QueryFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundsRequest.ProtoReflect.Descriptor instead.
func (*QueryFundsRequest) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryFundsRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Funds         []*Fund                `protobuf:"bytes,1,rep,name=funds,proto3" json:"funds,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundsResponse) Reset() {
	*x = QueryFundsResponse{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundsResponse) ProtoMessage() {}

func (x *QueryFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundsResponse.ProtoReflect.Descriptor instead.
func (*QueryFundsResponse) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryFundsResponse) GetFunds() []*Fund {
	if x != nil {
		return x.Funds
	}
	return nil
}

func (x *QueryFundsResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryFundsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FundType               `protobuf:"varint,1,opt,name=type,proto3,enum=uagd.fund.v1.FundType" json:"type,omitempty"`
	RegionId      string                 `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundsByTypeRequest) Reset() {
	*x = QueryFundsByTypeRequest{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundsByTypeRequest) ProtoMessage() {}

func (x *QueryFundsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundsByTypeRequest.ProtoReflect.Descriptor instead.
func (*QueryFundsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryFundsByTypeRequest) GetType() FundType {
	if x != nil {
		return x.Type
	}
	return FundType_FUND_TYPE_REGION
}

func (x *QueryFundsByTypeRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

type QueryFundsByTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Funds         []*Fund                `protobuf:"bytes,1,rep,name=funds,proto3" json:"funds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFundsByTypeResponse) Reset() {
	*x = QueryFundsByTypeResponse{}
	mi := &file_uagd_fund_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFundsByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFundsByTypeResponse) ProtoMessage() {}

func (x *QueryFundsByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFundsByTypeResponse.ProtoReflect.Descriptor instead.
func (*QueryFundsByTypeResponse) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryFundsByTypeResponse) GetFunds() []*Fund {
	if x != nil {
		return x.Funds
	}
	return nil
}

var File_uagd_fund_v1_query_proto protoreflect.FileDescriptor

const file_uagd_fund_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x18uagd/fund/v1/query.proto\x12\fuagd.fund.v1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17uagd/fund/v1/fund.proto\",\n" +
	"\x10QueryFundRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\";\n" +
	"\x11QueryFundResponse\x12&\n" +
	"\x04fund\x18\x01 \x01(\v2\x12.uagd.fund.v1.FundR\x04fund\"[\n" +
	"\x11QueryFundsRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x87\x01\n" +
	"\x12QueryFundsResponse\x12(\n" +
	"\x05funds\x18\x01 \x03(\v2\x12.uagd.fund.v1.FundR\x05funds\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"b\n" +
	"\x17QueryFundsByTypeRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.uagd.fund.v1.FundTypeR\x04type\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\tR\bregionId\"D\n" +
	"\x18QueryFundsByTypeResponse\x12(\n" +
	"\x05funds\x18\x01 \x03(\v2\x12.uagd.fund.v1.FundR\x05funds2\xe4\x02\n" +
	"\x05Query\x12n\n" +
	"\x04Fund\x12\x1e.uagd.fund.v1.QueryFundRequest\x1a\x1f.uagd.fund.v1.QueryFundResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/uagd/fund/v1/funds/{address}\x12g\n" +
	"\x05Funds\x12\x1f.uagd.fund.v1.QueryFundsRequest\x1a .uagd.fund.v1.QueryFundsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/uagd/fund/v1/funds\x12\x81\x01\n" +
	"\vFundsByType\x12%.uagd.fund.v1.QueryFundsByTypeRequest\x1a&.uagd.fund.v1.QueryFundsByTypeResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/uagd/fund/v1/funds/by_typeB\x13Z\x11uagd/x/fund/typesb\x06proto3"

var (
	file_uagd_fund_v1_query_proto_rawDescOnce sync.Once
	file_uagd_fund_v1_query_proto_rawDescData []byte
)

func file_uagd_fund_v1_query_proto_rawDescGZIP() []byte {
	file_uagd_fund_v1_query_proto_rawDescOnce.Do(func() {
		file_uagd_fund_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_query_proto_rawDesc), len(file_uagd_fund_v1_query_proto_rawDesc)))
	})
	return file_uagd_fund_v1_query_proto_rawDescData
}

var file_uagd_fund_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_uagd_fund_v1_query_proto_goTypes = []any{
	(*QueryFundRequest)(nil),         // 0: uagd.fund.v1.QueryFundRequest
	(*QueryFundResponse)(nil),        // 1: uagd.fund.v1.QueryFundResponse
	(*QueryFundsRequest)(nil),        // 2: uagd.fund.v1.QueryFundsRequest
	(*QueryFundsResponse)(nil),       // 3: uagd.fund.v1.QueryFundsResponse
	(*QueryFundsByTypeRequest)(nil),  // 4: uagd.fund.v1.QueryFundsByTypeRequest
	(*QueryFundsByTypeResponse)(nil), // 5: uagd.fund.v1.QueryFundsByTypeResponse
	(*Fund)(nil),                     // 6: uagd.fund.v1.Fund
	(*query.PageRequest)(nil),        // 7: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),       // 8: cosmos.base.query.v1beta1.PageResponse
	(FundType)(0),                    // 9: uagd.fund.v1.FundType
}
var file_uagd_fund_v1_query_proto_depIdxs = []int32{
	6, // 0: uagd.fund.v1.QueryFundResponse.fund:type_name -> uagd.fund.v1.Fund
	7, // 1: uagd.fund.v1.QueryFundsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	6, // 2: uagd.fund.v1.QueryFundsResponse.funds:type_name -> uagd.fund.v1.Fund
	8, // 3: uagd.fund.v1.QueryFundsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	9, // 4: uagd.fund.v1.QueryFundsByTypeRequest.type:type_name -> uagd.fund.v1.FundType
	6, // 5: uagd.fund.v1.QueryFundsByTypeResponse.funds:type_name -> uagd.fund.v1.Fund
	0, // 6: uagd.fund.v1.Query.Fund:input_type -> uagd.fund.v1.QueryFundRequest
	2, // 7: uagd.fund.v1.Query.Funds:input_type -> uagd.fund.v1.QueryFundsRequest
	4, // 8: uagd.fund.v1.Query.FundsByType:input_type -> uagd.fund.v1.QueryFundsByTypeRequest
	1, // 9: uagd.fund.v1.Query.Fund:output_type -> uagd.fund.v1.QueryFundResponse
	3, // 10: uagd.fund.v1.Query.Funds:output_type -> uagd.fund.v1.QueryFundsResponse
	5, // 11: uagd.fund.v1.Query.FundsByType:output_type -> uagd.fund.v1.QueryFundsByTypeResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_uagd_fund_v1_query_proto_init() }
func file_uagd_fund_v1_query_proto_init() {
	if File_uagd_fund_v1_query_proto != nil {
		return
	}
	file_uagd_fund_v1_fund_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_query_proto_rawDesc), len(file_uagd_fund_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uagd_fund_v1_query_proto_goTypes,
		DependencyIndexes: file_uagd_fund_v1_query_proto_depIdxs,
		MessageInfos:      file_uagd_fund_v1_query_proto_msgTypes,
	}.Build()
	File_uagd_fund_v1_query_proto = out.File
	file_uagd_fund_v1_query_proto_goTypes = nil
	file_uagd_fund_v1_query_proto_depIdxs = nil
}
