// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/fund/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgExecuteFundPlan executes a fund plan after authorization.
type MsgExecuteFundPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Plan          *FundPlan              `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgExecuteFundPlan) Reset() {
	*x = MsgExecuteFundPlan{}
	mi := &file_uagd_fund_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgExecuteFundPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteFundPlan) ProtoMessage() {}

func (x *MsgExecuteFundPlan) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteFundPlan.ProtoReflect.Descriptor instead.
func (*MsgExecuteFundPlan) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgExecuteFundPlan) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgExecuteFundPlan) GetPlan() *FundPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type MsgExecuteFundPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgExecuteFundPlanResponse) Reset() {
	*x = MsgExecuteFundPlanResponse{}
	mi := &file_uagd_fund_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgExecuteFundPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteFundPlanResponse) ProtoMessage() {}

func (x *MsgExecuteFundPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_fund_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteFundPlanResponse.ProtoReflect.Descriptor instead.
func (*MsgExecuteFundPlanResponse) Descriptor() ([]byte, []int) {
	return file_uagd_fund_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_uagd_fund_v1_tx_proto protoreflect.FileDescriptor

const file_uagd_fund_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x15uagd/fund/v1/tx.proto\x12\fuagd.fund.v1\x1a\x11amino/amino.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x17uagd/fund/v1/fund.proto\"\xb1\x01\n" +
	"\x12MsgExecuteFundPlan\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x120\n" +
	"\x04plan\x18\x02 \x01(\v2\x16.uagd.fund.v1.FundPlanB\x04\xc8\xde\x1f\x00R\x04plan:1\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1euagd/x/fund/MsgExecuteFundPlan\"\x1c\n" +
	"\x1aMsgExecuteFundPlanResponse2k\n" +
	"\x03Msg\x12]\n" +
	"\x0fExecuteFundPlan\x12 .uagd.fund.v1.MsgExecuteFundPlan\x1a(.uagd.fund.v1.MsgExecuteFundPlanResponse\x1a\x05\x80\xe7\xb0*\x01B\x13Z\x11uagd/x/fund/typesb\x06proto3"

var (
	file_uagd_fund_v1_tx_proto_rawDescOnce sync.Once
	file_uagd_fund_v1_tx_proto_rawDescData []byte
)

func file_uagd_fund_v1_tx_proto_rawDescGZIP() []byte {
	file_uagd_fund_v1_tx_proto_rawDescOnce.Do(func() {
		file_uagd_fund_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_tx_proto_rawDesc), len(file_uagd_fund_v1_tx_proto_rawDesc)))
	})
	return file_uagd_fund_v1_tx_proto_rawDescData
}

var file_uagd_fund_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uagd_fund_v1_tx_proto_goTypes = []any{
	(*MsgExecuteFundPlan)(nil),         // 0: uagd.fund.v1.MsgExecuteFundPlan
	(*MsgExecuteFundPlanResponse)(nil), // 1: uagd.fund.v1.MsgExecuteFundPlanResponse
	(*FundPlan)(nil),                   // 2: uagd.fund.v1.FundPlan
}
var file_uagd_fund_v1_tx_proto_depIdxs = []int32{
	2, // 0: uagd.fund.v1.MsgExecuteFundPlan.plan:type_name -> uagd.fund.v1.FundPlan
	0, // 1: uagd.fund.v1.Msg.ExecuteFundPlan:input_type -> uagd.fund.v1.MsgExecuteFundPlan
	1, // 2: uagd.fund.v1.Msg.ExecuteFundPlan:output_type -> uagd.fund.v1.MsgExecuteFundPlanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_uagd_fund_v1_tx_proto_init() }
func file_uagd_fund_v1_tx_proto_init() {
	if File_uagd_fund_v1_tx_proto != nil {
		return
	}
	file_uagd_fund_v1_fund_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_fund_v1_tx_proto_rawDesc), len(file_uagd_fund_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uagd_fund_v1_tx_proto_goTypes,
		DependencyIndexes: file_uagd_fund_v1_tx_proto_depIdxs,
		MessageInfos:      file_uagd_fund_v1_tx_proto_msgTypes,
	}.Build()
	File_uagd_fund_v1_tx_proto = out.File
	file_uagd_fund_v1_tx_proto_goTypes = nil
	file_uagd_fund_v1_tx_proto_depIdxs = nil
}
