// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/citizen/v1/citizen.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CitizenRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RegionId      string                 `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CitizenRegion) Reset() {
	*x = CitizenRegion{}
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitizenRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenRegion) ProtoMessage() {}

func (x *CitizenRegion) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenRegion.ProtoReflect.Descriptor instead.
func (*CitizenRegion) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_citizen_proto_rawDescGZIP(), []int{0}
}

func (x *CitizenRegion) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CitizenRegion) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

type Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrars    []string               `protobuf:"bytes,1,rep,name=registrars,proto3" json:"registrars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_citizen_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetRegistrars() []string {
	if x != nil {
		return x.Registrars
	}
	return nil
}

type GenesisState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Entries       []*CitizenRegion       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_citizen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_citizen_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetEntries() []*CitizenRegion {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_uagd_citizen_v1_citizen_proto protoreflect.FileDescriptor

const file_uagd_citizen_v1_citizen_proto_rawDesc = "" +
	"\n" +
	"\x1duagd/citizen/v1/citizen.proto\x12\x0fuagd.citizen.v1\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"`\n" +
	"\rCitizenRegion\x122\n" +
	"\aaddress\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\aaddress\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\tR\bregionId\"B\n" +
	"\x06Params\x128\n" +
	"\n" +
	"registrars\x18\x01 \x03(\tB\x18Ҵ-\x14cosmos.AddressStringR\n" +
	"registrars\"\x85\x01\n" +
	"\fGenesisState\x125\n" +
	"\x06params\x18\x01 \x01(\v2\x17.uagd.citizen.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12>\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.uagd.citizen.v1.CitizenRegionB\x04\xc8\xde\x1f\x00R\aentriesB\x16Z\x14uagd/x/citizen/typesb\x06proto3"

var (
	file_uagd_citizen_v1_citizen_proto_rawDescOnce sync.Once
	file_uagd_citizen_v1_citizen_proto_rawDescData []byte
)

func file_uagd_citizen_v1_citizen_proto_rawDescGZIP() []byte {
	file_uagd_citizen_v1_citizen_proto_rawDescOnce.Do(func() {
		file_uagd_citizen_v1_citizen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_citizen_v1_citizen_proto_rawDesc), len(file_uagd_citizen_v1_citizen_proto_rawDesc)))
	})
	return file_uagd_citizen_v1_citizen_proto_rawDescData
}

var file_uagd_citizen_v1_citizen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_uagd_citizen_v1_citizen_proto_goTypes = []any{
	(*CitizenRegion)(nil), // 0: uagd.citizen.v1.CitizenRegion
	(*Params)(nil),        // 1: uagd.citizen.v1.Params
	(*GenesisState)(nil),  // 2: uagd.citizen.v1.GenesisState
}
var file_uagd_citizen_v1_citizen_proto_depIdxs = []int32{
	1, // 0: uagd.citizen.v1.GenesisState.params:type_name -> uagd.citizen.v1.Params
	0, // 1: uagd.citizen.v1.GenesisState.entries:type_name -> uagd.citizen.v1.CitizenRegion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_uagd_citizen_v1_citizen_proto_init() }
func file_uagd_citizen_v1_citizen_proto_init() {
	if File_uagd_citizen_v1_citizen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_citizen_v1_citizen_proto_rawDesc), len(file_uagd_citizen_v1_citizen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uagd_citizen_v1_citizen_proto_goTypes,
		DependencyIndexes: file_uagd_citizen_v1_citizen_proto_depIdxs,
		MessageInfos:      file_uagd_citizen_v1_citizen_proto_msgTypes,
	}.Build()
	File_uagd_citizen_v1_citizen_proto = out.File
	file_uagd_citizen_v1_citizen_proto_goTypes = nil
	file_uagd_citizen_v1_citizen_proto_depIdxs = nil
}
