// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/citizen/v1/query.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRegionByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRegionByAddressRequest) Reset() {
	*x = QueryRegionByAddressRequest{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRegionByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRegionByAddressRequest) ProtoMessage() {}

func (x *QueryRegionByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRegionByAddressRequest.ProtoReflect.Descriptor instead.
func (*QueryRegionByAddressRequest) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRegionByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryRegionByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRegionByAddressResponse) Reset() {
	*x = QueryRegionByAddressResponse{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRegionByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRegionByAddressResponse) ProtoMessage() {}

func (x *QueryRegionByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRegionByAddressResponse.ProtoReflect.Descriptor instead.
func (*QueryRegionByAddressResponse) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRegionByAddressResponse) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

type QueryAddressesByRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAddressesByRegionRequest) Reset() {
	*x = QueryAddressesByRegionRequest{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAddressesByRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAddressesByRegionRequest) ProtoMessage() {}

func (x *QueryAddressesByRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAddressesByRegionRequest.ProtoReflect.Descriptor instead.
func (*QueryAddressesByRegionRequest) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAddressesByRegionRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

type QueryAddressesByRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAddressesByRegionResponse) Reset() {
	*x = QueryAddressesByRegionResponse{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAddressesByRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAddressesByRegionResponse) ProtoMessage() {}

func (x *QueryAddressesByRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAddressesByRegionResponse.ProtoReflect.Descriptor instead.
func (*QueryAddressesByRegionResponse) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAddressesByRegionResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_citizen_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_uagd_citizen_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_uagd_citizen_v1_query_proto protoreflect.FileDescriptor

const file_uagd_citizen_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1buagd/citizen/v1/query.proto\x12\x0fuagd.citizen.v1\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1duagd/citizen/v1/citizen.proto\"Q\n" +
	"\x1bQueryRegionByAddressRequest\x122\n" +
	"\aaddress\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\aaddress\";\n" +
	"\x1cQueryRegionByAddressResponse\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\"<\n" +
	"\x1dQueryAddressesByRegionRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\"X\n" +
	"\x1eQueryAddressesByRegionResponse\x126\n" +
	"\taddresses\x18\x01 \x03(\tB\x18Ҵ-\x14cosmos.AddressStringR\taddresses\"\x14\n" +
	"\x12QueryParamsRequest\"L\n" +
	"\x13QueryParamsResponse\x125\n" +
	"\x06params\x18\x01 \x01(\v2\x17.uagd.citizen.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params2\xda\x02\n" +
	"\x05Query\x12v\n" +
	"\x0fRegionByAddress\x12,.uagd.citizen.v1.QueryRegionByAddressRequest\x1a-.uagd.citizen.v1.QueryRegionByAddressResponse\"\x06ʴ-\x02v1\x12|\n" +
	"\x11AddressesByRegion\x12..uagd.citizen.v1.QueryAddressesByRegionRequest\x1a/.uagd.citizen.v1.QueryAddressesByRegionResponse\"\x06ʴ-\x02v1\x12[\n" +
	"\x06Params\x12#.uagd.citizen.v1.QueryParamsRequest\x1a$.uagd.citizen.v1.QueryParamsResponse\"\x06ʴ-\x02v1B\x16Z\x14uagd/x/citizen/typesb\x06proto3"

var (
	file_uagd_citizen_v1_query_proto_rawDescOnce sync.Once
	file_uagd_citizen_v1_query_proto_rawDescData []byte
)

func file_uagd_citizen_v1_query_proto_rawDescGZIP() []byte {
	file_uagd_citizen_v1_query_proto_rawDescOnce.Do(func() {
		file_uagd_citizen_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_citizen_v1_query_proto_rawDesc), len(file_uagd_citizen_v1_query_proto_rawDesc)))
	})
	return file_uagd_citizen_v1_query_proto_rawDescData
}

var file_uagd_citizen_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_uagd_citizen_v1_query_proto_goTypes = []any{
	(*QueryRegionByAddressRequest)(nil),    // 0: uagd.citizen.v1.QueryRegionByAddressRequest
	(*QueryRegionByAddressResponse)(nil),   // 1: uagd.citizen.v1.QueryRegionByAddressResponse
	(*QueryAddressesByRegionRequest)(nil),  // 2: uagd.citizen.v1.QueryAddressesByRegionRequest
	(*QueryAddressesByRegionResponse)(nil), // 3: uagd.citizen.v1.QueryAddressesByRegionResponse
	(*QueryParamsRequest)(nil),             // 4: uagd.citizen.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),            // 5: uagd.citizen.v1.QueryParamsResponse
	(*Params)(nil),                         // 6: uagd.citizen.v1.Params
}
var file_uagd_citizen_v1_query_proto_depIdxs = []int32{
	6, // 0: uagd.citizen.v1.QueryParamsResponse.params:type_name -> uagd.citizen.v1.Params
	0, // 1: uagd.citizen.v1.Query.RegionByAddress:input_type -> uagd.citizen.v1.QueryRegionByAddressRequest
	2, // 2: uagd.citizen.v1.Query.AddressesByRegion:input_type -> uagd.citizen.v1.QueryAddressesByRegionRequest
	4, // 3: uagd.citizen.v1.Query.Params:input_type -> uagd.citizen.v1.QueryParamsRequest
	1, // 4: uagd.citizen.v1.Query.RegionByAddress:output_type -> uagd.citizen.v1.QueryRegionByAddressResponse
	3, // 5: uagd.citizen.v1.Query.AddressesByRegion:output_type -> uagd.citizen.v1.QueryAddressesByRegionResponse
	5, // 6: uagd.citizen.v1.Query.Params:output_type -> uagd.citizen.v1.QueryParamsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_uagd_citizen_v1_query_proto_init() }
func file_uagd_citizen_v1_query_proto_init() {
	if File_uagd_citizen_v1_query_proto != nil {
		return
	}
	file_uagd_citizen_v1_citizen_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_citizen_v1_query_proto_rawDesc), len(file_uagd_citizen_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uagd_citizen_v1_query_proto_goTypes,
		DependencyIndexes: file_uagd_citizen_v1_query_proto_depIdxs,
		MessageInfos:      file_uagd_citizen_v1_query_proto_msgTypes,
	}.Build()
	File_uagd_citizen_v1_query_proto = out.File
	file_uagd_citizen_v1_query_proto_goTypes = nil
	file_uagd_citizen_v1_query_proto_depIdxs = nil
}
