// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uag/citizen/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetCitizenRegion struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RegionId  string `protobuf:"bytes,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
}

func (m *MsgSetCitizenRegion) Reset()         { *m = MsgSetCitizenRegion{} }
func (m *MsgSetCitizenRegion) String() string { return proto.CompactTextString(m) }
func (*MsgSetCitizenRegion) ProtoMessage()    {}
func (*MsgSetCitizenRegion) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec4703d6e5a4ab2b, []int{0}
}
func (m *MsgSetCitizenRegion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCitizenRegion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCitizenRegion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCitizenRegion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCitizenRegion.Merge(m, src)
}
func (m *MsgSetCitizenRegion) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCitizenRegion) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCitizenRegion.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCitizenRegion proto.InternalMessageInfo

func (m *MsgSetCitizenRegion) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetCitizenRegion) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSetCitizenRegion) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

type MsgSetCitizenRegionResponse struct {
}

func (m *MsgSetCitizenRegionResponse) Reset()         { *m = MsgSetCitizenRegionResponse{} }
func (m *MsgSetCitizenRegionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetCitizenRegionResponse) ProtoMessage()    {}
func (*MsgSetCitizenRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec4703d6e5a4ab2b, []int{1}
}
func (m *MsgSetCitizenRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCitizenRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCitizenRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCitizenRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCitizenRegionResponse.Merge(m, src)
}
func (m *MsgSetCitizenRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCitizenRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCitizenRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCitizenRegionResponse proto.InternalMessageInfo

type MsgClearCitizenRegion struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgClearCitizenRegion) Reset()         { *m = MsgClearCitizenRegion{} }
func (m *MsgClearCitizenRegion) String() string { return proto.CompactTextString(m) }
func (*MsgClearCitizenRegion) ProtoMessage()    {}
func (*MsgClearCitizenRegion) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec4703d6e5a4ab2b, []int{2}
}
func (m *MsgClearCitizenRegion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClearCitizenRegion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClearCitizenRegion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClearCitizenRegion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClearCitizenRegion.Merge(m, src)
}
func (m *MsgClearCitizenRegion) XXX_Size() int {
	return m.Size()
}
func (m *MsgClearCitizenRegion) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClearCitizenRegion.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClearCitizenRegion proto.InternalMessageInfo

func (m *MsgClearCitizenRegion) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgClearCitizenRegion) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgClearCitizenRegionResponse struct {
}

func (m *MsgClearCitizenRegionResponse) Reset()         { *m = MsgClearCitizenRegionResponse{} }
func (m *MsgClearCitizenRegionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClearCitizenRegionResponse) ProtoMessage()    {}
func (*MsgClearCitizenRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec4703d6e5a4ab2b, []int{3}
}
func (m *MsgClearCitizenRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClearCitizenRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClearCitizenRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClearCitizenRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClearCitizenRegionResponse.Merge(m, src)
}
func (m *MsgClearCitizenRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClearCitizenRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClearCitizenRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClearCitizenRegionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetCitizenRegion)(nil), "uag.citizen.v1.MsgSetCitizenRegion")
	proto.RegisterType((*MsgSetCitizenRegionResponse)(nil), "uag.citizen.v1.MsgSetCitizenRegionResponse")
	proto.RegisterType((*MsgClearCitizenRegion)(nil), "uag.citizen.v1.MsgClearCitizenRegion")
	proto.RegisterType((*MsgClearCitizenRegionResponse)(nil), "uag.citizen.v1.MsgClearCitizenRegionResponse")
}

func init() { proto.RegisterFile("uag/citizen/v1/tx.proto", fileDescriptor_ec4703d6e5a4ab2b) }

var fileDescriptor_ec4703d6e5a4ab2b = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4d, 0x4c, 0xd7,
	0x4f, 0xce, 0x2c, 0xc9, 0xac, 0x4a, 0xcd, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2b, 0x4d, 0x4c, 0xd7, 0x83, 0x4a, 0xe8, 0x95, 0x19, 0x4a, 0x09,
	0x26, 0xe6, 0x66, 0xe6, 0xe5, 0xeb, 0x83, 0x49, 0x88, 0x12, 0x29, 0xf1, 0xe4, 0xfc, 0xe2, 0xdc,
	0xfc, 0x62, 0xfd, 0xdc, 0xe2, 0x74, 0x90, 0xd6, 0xdc, 0xe2, 0x74, 0xa8, 0x84, 0x24, 0x44, 0x22,
	0x1e, 0xcc, 0xd3, 0x87, 0x70, 0x20, 0x52, 0x4a, 0x57, 0x18, 0xb9, 0x84, 0x7d, 0x8b, 0xd3, 0x83,
	0x53, 0x4b, 0x9c, 0x21, 0x66, 0x07, 0xa5, 0xa6, 0x67, 0xe6, 0xe7, 0x09, 0x99, 0x71, 0x71, 0x26,
	0x96, 0x96, 0x64, 0xe4, 0x17, 0x65, 0x96, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x3a, 0x49,
	0x5c, 0xda, 0xa2, 0x2b, 0x02, 0xd5, 0xec, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c, 0x1c, 0x5c, 0x52,
	0x94, 0x99, 0x97, 0x1e, 0x84, 0x50, 0x2a, 0x64, 0xc4, 0xc5, 0x9e, 0x08, 0x91, 0x93, 0x60, 0x22,
	0xa0, 0x0b, 0xa6, 0x50, 0x48, 0x9a, 0x8b, 0xb3, 0x08, 0x6c, 0x6b, 0x7c, 0x66, 0x8a, 0x04, 0x33,
	0x48, 0x57, 0x10, 0x07, 0x44, 0xc0, 0x33, 0xc5, 0xca, 0xa4, 0xe9, 0xf9, 0x06, 0x2d, 0x84, 0x05,
	0x5d, 0xcf, 0x37, 0x68, 0x29, 0x82, 0xc2, 0xa8, 0x02, 0x1e, 0x4a, 0x58, 0x9c, 0xaf, 0x24, 0xcb,
	0x25, 0x8d, 0x45, 0x38, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x69, 0x37, 0x23, 0x97,
	0xa8, 0x6f, 0x71, 0xba, 0x73, 0x4e, 0x6a, 0x62, 0xd1, 0x80, 0xf9, 0xdb, 0xca, 0x0c, 0xd3, 0x6b,
	0xca, 0x18, 0x5e, 0xc3, 0x74, 0xa3, 0x92, 0x3c, 0x97, 0x2c, 0x56, 0x09, 0x98, 0xf7, 0x8c, 0xee,
	0x31, 0x72, 0x31, 0xfb, 0x16, 0xa7, 0x0b, 0xa5, 0x70, 0x09, 0x60, 0x44, 0xac, 0xb2, 0x1e, 0x6a,
	0x42, 0xd2, 0xc3, 0x12, 0x4e, 0x52, 0xda, 0x44, 0x28, 0x82, 0xd9, 0x26, 0x94, 0xc5, 0x25, 0x84,
	0x25, 0x20, 0x55, 0xb1, 0x18, 0x81, 0xa9, 0x4c, 0x4a, 0x97, 0x28, 0x65, 0x30, 0xbb, 0xa4, 0x58,
	0x1b, 0x9e, 0x6f, 0xd0, 0x62, 0x74, 0xd2, 0x3d, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6,
	0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39,
	0x86, 0x28, 0x61, 0xd4, 0x00, 0x2c, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0xa7, 0x75, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xaf, 0xc2, 0xe9, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetCitizenRegion(ctx context.Context, in *MsgSetCitizenRegion, opts ...grpc.CallOption) (*MsgSetCitizenRegionResponse, error)
	ClearCitizenRegion(ctx context.Context, in *MsgClearCitizenRegion, opts ...grpc.CallOption) (*MsgClearCitizenRegionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetCitizenRegion(ctx context.Context, in *MsgSetCitizenRegion, opts ...grpc.CallOption) (*MsgSetCitizenRegionResponse, error) {
	out := new(MsgSetCitizenRegionResponse)
	err := c.cc.Invoke(ctx, "/uag.citizen.v1.Msg/SetCitizenRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClearCitizenRegion(ctx context.Context, in *MsgClearCitizenRegion, opts ...grpc.CallOption) (*MsgClearCitizenRegionResponse, error) {
	out := new(MsgClearCitizenRegionResponse)
	err := c.cc.Invoke(ctx, "/uag.citizen.v1.Msg/ClearCitizenRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetCitizenRegion(context.Context, *MsgSetCitizenRegion) (*MsgSetCitizenRegionResponse, error)
	ClearCitizenRegion(context.Context, *MsgClearCitizenRegion) (*MsgClearCitizenRegionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetCitizenRegion(ctx context.Context, req *MsgSetCitizenRegion) (*MsgSetCitizenRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCitizenRegion not implemented")
}
func (*UnimplementedMsgServer) ClearCitizenRegion(ctx context.Context, req *MsgClearCitizenRegion) (*MsgClearCitizenRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearCitizenRegion not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetCitizenRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetCitizenRegion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetCitizenRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uag.citizen.v1.Msg/SetCitizenRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetCitizenRegion(ctx, req.(*MsgSetCitizenRegion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClearCitizenRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearCitizenRegion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClearCitizenRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uag.citizen.v1.Msg/ClearCitizenRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClearCitizenRegion(ctx, req.(*MsgClearCitizenRegion))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uag.citizen.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCitizenRegion",
			Handler:    _Msg_SetCitizenRegion_Handler,
		},
		{
			MethodName: "ClearCitizenRegion",
			Handler:    _Msg_ClearCitizenRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uag/citizen/v1/tx.proto",
}

func (m *MsgSetCitizenRegion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCitizenRegion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCitizenRegion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetCitizenRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCitizenRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCitizenRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClearCitizenRegion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClearCitizenRegion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClearCitizenRegion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClearCitizenRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClearCitizenRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClearCitizenRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetCitizenRegion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetCitizenRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClearCitizenRegion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClearCitizenRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetCitizenRegion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCitizenRegion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCitizenRegion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCitizenRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCitizenRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCitizenRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClearCitizenRegion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClearCitizenRegion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClearCitizenRegion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClearCitizenRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClearCitizenRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClearCitizenRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
