// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uagd/growth/v1/growth.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RegionMetric captures official economic indicators for a region and period.
type RegionMetric struct {
	RegionId string `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period   string `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	// Index values are decimals in the range [0, 2].
	// NOTE: Cosmos SDK v0.53 uses cosmossdk.io/math.LegacyDec (sdk.Dec was removed).
	TaxIndex     cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=tax_index,json=taxIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"tax_index"`
	GdpIndex     cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=gdp_index,json=gdpIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"gdp_index"`
	ExportsIndex cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=exports_index,json=exportsIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"exports_index"`
}

func (m *RegionMetric) Reset()         { *m = RegionMetric{} }
func (m *RegionMetric) String() string { return proto.CompactTextString(m) }
func (*RegionMetric) ProtoMessage()    {}
func (*RegionMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_46fa447484d84272, []int{0}
}
func (m *RegionMetric) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegionMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegionMetric.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegionMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionMetric.Merge(m, src)
}
func (m *RegionMetric) XXX_Size() int {
	return m.Size()
}
func (m *RegionMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionMetric.DiscardUnknown(m)
}

var xxx_messageInfo_RegionMetric proto.InternalMessageInfo

func (m *RegionMetric) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *RegionMetric) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

// GrowthScore stores derived multipliers for a region and period.
type GrowthScore struct {
	RegionId             string                      `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period               string                      `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Score                cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=score,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"score"`
	DelegationMultiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=delegation_multiplier,json=delegationMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"delegation_multiplier"`
	PayrollMultiplier    cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=payroll_multiplier,json=payrollMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"payroll_multiplier"`
}

func (m *GrowthScore) Reset()         { *m = GrowthScore{} }
func (m *GrowthScore) String() string { return proto.CompactTextString(m) }
func (*GrowthScore) ProtoMessage()    {}
func (*GrowthScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_46fa447484d84272, []int{1}
}
func (m *GrowthScore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GrowthScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GrowthScore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GrowthScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrowthScore.Merge(m, src)
}
func (m *GrowthScore) XXX_Size() int {
	return m.Size()
}
func (m *GrowthScore) XXX_DiscardUnknown() {
	xxx_messageInfo_GrowthScore.DiscardUnknown(m)
}

var xxx_messageInfo_GrowthScore proto.InternalMessageInfo

func (m *GrowthScore) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *GrowthScore) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

// Occupation stores the occupation percentage for a region and period.
type Occupation struct {
	RegionId   string                      `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period     string                      `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Occupation cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=occupation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"occupation"`
}

func (m *Occupation) Reset()         { *m = Occupation{} }
func (m *Occupation) String() string { return proto.CompactTextString(m) }
func (*Occupation) ProtoMessage()    {}
func (*Occupation) Descriptor() ([]byte, []int) {
	return fileDescriptor_46fa447484d84272, []int{2}
}
func (m *Occupation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Occupation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Occupation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Occupation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occupation.Merge(m, src)
}
func (m *Occupation) XXX_Size() int {
	return m.Size()
}
func (m *Occupation) XXX_DiscardUnknown() {
	xxx_messageInfo_Occupation.DiscardUnknown(m)
}

var xxx_messageInfo_Occupation proto.InternalMessageInfo

func (m *Occupation) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *Occupation) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

// Params defines module parameters.
type Params struct {
	CurrentPeriod    string `protobuf:"bytes,1,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
	Oracle           string `protobuf:"bytes,2,opt,name=oracle,proto3" json:"oracle,omitempty"`
	NationalRegionId string `protobuf:"bytes,3,opt,name=national_region_id,json=nationalRegionId,proto3" json:"national_region_id,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_46fa447484d84272, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCurrentPeriod() string {
	if m != nil {
		return m.CurrentPeriod
	}
	return ""
}

func (m *Params) GetOracle() string {
	if m != nil {
		return m.Oracle
	}
	return ""
}

func (m *Params) GetNationalRegionId() string {
	if m != nil {
		return m.NationalRegionId
	}
	return ""
}

// GenesisState defines the growth module's genesis state.
type GenesisState struct {
	Params         Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Metrics        []RegionMetric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics"`
	Scores         []GrowthScore  `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores"`
	OccupationList []Occupation   `protobuf:"bytes,4,rep,name=occupation_list,json=occupationList,proto3" json:"occupation_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_46fa447484d84272, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMetrics() []RegionMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *GenesisState) GetScores() []GrowthScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *GenesisState) GetOccupationList() []Occupation {
	if m != nil {
		return m.OccupationList
	}
	return nil
}

func init() {
	proto.RegisterType((*RegionMetric)(nil), "uagd.growth.v1.RegionMetric")
	proto.RegisterType((*GrowthScore)(nil), "uagd.growth.v1.GrowthScore")
	proto.RegisterType((*Occupation)(nil), "uagd.growth.v1.Occupation")
	proto.RegisterType((*Params)(nil), "uagd.growth.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "uagd.growth.v1.GenesisState")
}

func init() { proto.RegisterFile("uagd/growth/v1/growth.proto", fileDescriptor_46fa447484d84272) }

var fileDescriptor_46fa447484d84272 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xe3, 0xb4, 0xf5, 0xd7, 0xde, 0xfe, 0xf9, 0x60, 0x08, 0x95, 0x49, 0x90, 0x5b, 0x45,
	0x42, 0xea, 0x82, 0x38, 0xa4, 0xb0, 0x41, 0x62, 0x43, 0x54, 0x29, 0x8a, 0xd4, 0x42, 0x71, 0x24,
	0x16, 0x6c, 0xcc, 0x60, 0x0f, 0xee, 0x08, 0xc7, 0x63, 0xcd, 0x4c, 0x4a, 0xf2, 0x06, 0xec, 0x60,
	0xc1, 0xa3, 0x74, 0xc7, 0x0b, 0x74, 0x59, 0x55, 0x42, 0x42, 0x2c, 0x2a, 0x94, 0xbc, 0x08, 0xf2,
	0xcc, 0xa4, 0x0e, 0x59, 0x7a, 0xe7, 0xb9, 0x77, 0xce, 0xef, 0x1e, 0x1f, 0xd9, 0x17, 0x1a, 0x23,
	0x1c, 0x47, 0xed, 0x98, 0xb3, 0xcf, 0xf2, 0xac, 0x7d, 0xde, 0x31, 0x4f, 0x5e, 0xc6, 0x99, 0x64,
	0x68, 0x27, 0x6f, 0x7a, 0xa6, 0x74, 0xde, 0xa9, 0x3f, 0x08, 0x99, 0x18, 0x32, 0x11, 0xa8, 0x6e,
	0x5b, 0x1f, 0xf4, 0xd5, 0x7a, 0x2d, 0x66, 0x31, 0xd3, 0xf5, 0xfc, 0x49, 0x57, 0x9b, 0x3f, 0xaa,
	0xb0, 0xe5, 0x93, 0x98, 0xb2, 0xf4, 0x84, 0x48, 0x4e, 0x43, 0xd4, 0x80, 0x0d, 0xae, 0xce, 0x01,
	0x8d, 0x1c, 0x6b, 0xdf, 0x3a, 0xd8, 0xf0, 0xd7, 0x75, 0xa1, 0x1f, 0xa1, 0x5d, 0xb0, 0x33, 0xc2,
	0x29, 0x8b, 0x9c, 0xaa, 0xea, 0x98, 0x13, 0x7a, 0x05, 0x1b, 0x12, 0x8f, 0x03, 0x9a, 0x46, 0x64,
	0xec, 0xac, 0xe4, 0xad, 0x6e, 0xe7, 0xf2, 0x66, 0xaf, 0xf2, 0xfb, 0x66, 0xaf, 0xa1, 0x4d, 0x88,
	0xe8, 0x93, 0x47, 0x59, 0x7b, 0x88, 0xe5, 0x99, 0x77, 0x4c, 0x62, 0x1c, 0x4e, 0x8e, 0x48, 0x78,
	0x7d, 0xd1, 0x02, 0xe3, 0xf1, 0x88, 0x84, 0xfe, 0xba, 0xc4, 0xe3, 0x7e, 0x8e, 0xc8, 0x79, 0x71,
	0x94, 0x19, 0xde, 0x6a, 0x69, 0x5e, 0x1c, 0x65, 0x9a, 0xf7, 0x16, 0xb6, 0xc9, 0x38, 0x63, 0x5c,
	0x0a, 0xc3, 0x5c, 0x2b, 0xcb, 0xdc, 0x32, 0x1c, 0xc5, 0x6d, 0xfe, 0xac, 0xc2, 0x66, 0x4f, 0x85,
	0x3f, 0x08, 0x19, 0x27, 0xe5, 0xc2, 0xeb, 0xc1, 0x9a, 0xc8, 0xd5, 0xe5, 0x83, 0xd3, 0x7a, 0xf4,
	0x11, 0xee, 0x47, 0x24, 0x21, 0x31, 0x96, 0xb9, 0x83, 0xe1, 0x28, 0x91, 0x34, 0x4b, 0x28, 0xe1,
	0xe5, 0x13, 0xac, 0x15, 0xbc, 0x93, 0x5b, 0x1c, 0x7a, 0x0f, 0x28, 0xc3, 0x13, 0xce, 0x92, 0x64,
	0x71, 0x48, 0xe9, 0x48, 0xef, 0x1a, 0x58, 0x31, 0xa1, 0xf9, 0xdd, 0x02, 0x78, 0x1d, 0x86, 0xa3,
	0x4c, 0x8d, 0x2e, 0x17, 0xeb, 0x1b, 0x00, 0x76, 0x8b, 0x28, 0x9f, 0xed, 0x02, 0xa4, 0xf9, 0xd5,
	0x02, 0xfb, 0x14, 0x73, 0x3c, 0x14, 0xe8, 0x11, 0xec, 0x84, 0x23, 0xce, 0x49, 0x2a, 0x03, 0x33,
	0x5d, 0xfb, 0xda, 0x36, 0xd5, 0x53, 0x6d, 0xe2, 0x09, 0xd8, 0x8c, 0xe3, 0x30, 0x21, 0xda, 0x5c,
	0xd7, 0xb9, 0xbe, 0x68, 0xd5, 0x0c, 0xfd, 0x65, 0x14, 0x71, 0x22, 0xc4, 0x40, 0x72, 0x9a, 0xc6,
	0xbe, 0xb9, 0x87, 0x1e, 0x03, 0x4a, 0xd5, 0x34, 0x9c, 0x04, 0xc5, 0x4b, 0x2b, 0xfb, 0xfe, 0x9d,
	0x79, 0xc7, 0x37, 0x2f, 0xdf, 0xfc, 0x52, 0x85, 0xad, 0x1e, 0x49, 0x89, 0xa0, 0x62, 0x20, 0xb1,
	0x24, 0xe8, 0x19, 0xd8, 0x99, 0x72, 0xa8, 0xfc, 0x6c, 0x1e, 0xee, 0x7a, 0xff, 0x6e, 0x08, 0x4f,
	0xfb, 0xef, 0xae, 0xe6, 0x49, 0xf8, 0xe6, 0x2e, 0x7a, 0x01, 0xff, 0x0d, 0xd5, 0xef, 0x2f, 0x9c,
	0xea, 0xfe, 0xca, 0xc1, 0xe6, 0xe1, 0xc3, 0x65, 0xd9, 0xe2, 0x8e, 0x30, 0xe2, 0xb9, 0x04, 0x3d,
	0x07, 0x5b, 0x7d, 0x80, 0xc2, 0x59, 0x51, 0xe2, 0xc6, 0xb2, 0x78, 0xe1, 0x17, 0x99, 0x0f, 0xd6,
	0x02, 0xd4, 0x87, 0xff, 0x8b, 0x7c, 0x83, 0x84, 0x0a, 0xe9, 0xac, 0x2a, 0x46, 0x7d, 0x99, 0x51,
	0x7c, 0x0e, 0x06, 0xb1, 0x53, 0x08, 0x8f, 0xa9, 0x90, 0xdd, 0xd6, 0xe5, 0xd4, 0xb5, 0xae, 0xa6,
	0xae, 0xf5, 0x67, 0xea, 0x5a, 0xdf, 0x66, 0x6e, 0xe5, 0x6a, 0xe6, 0x56, 0x7e, 0xcd, 0xdc, 0xca,
	0xbb, 0x7b, 0x6a, 0x83, 0x8e, 0xe7, 0x3b, 0x54, 0x4e, 0x32, 0x22, 0x3e, 0xd8, 0x6a, 0xff, 0x3d,
	0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x7b, 0x90, 0x67, 0x5f, 0x05, 0x00, 0x00,
}

func (m *RegionMetric) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegionMetric) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegionMetric) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExportsIndex.Size()
		i -= size
		if _, err := m.ExportsIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.GdpIndex.Size()
		i -= size
		if _, err := m.GdpIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TaxIndex.Size()
		i -= size
		if _, err := m.TaxIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GrowthScore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GrowthScore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GrowthScore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PayrollMultiplier.Size()
		i -= size
		if _, err := m.PayrollMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DelegationMultiplier.Size()
		i -= size
		if _, err := m.DelegationMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Score.Size()
		i -= size
		if _, err := m.Score.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Occupation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Occupation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Occupation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Occupation.Size()
		i -= size
		if _, err := m.Occupation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NationalRegionId) > 0 {
		i -= len(m.NationalRegionId)
		copy(dAtA[i:], m.NationalRegionId)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.NationalRegionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Oracle) > 0 {
		i -= len(m.Oracle)
		copy(dAtA[i:], m.Oracle)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.Oracle)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CurrentPeriod) > 0 {
		i -= len(m.CurrentPeriod)
		copy(dAtA[i:], m.CurrentPeriod)
		i = encodeVarintGrowth(dAtA, i, uint64(len(m.CurrentPeriod)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OccupationList) > 0 {
		for iNdEx := len(m.OccupationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OccupationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGrowth(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Scores) > 0 {
		for iNdEx := len(m.Scores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Scores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGrowth(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Metrics) > 0 {
		for iNdEx := len(m.Metrics) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Metrics[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGrowth(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGrowth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGrowth(dAtA []byte, offset int, v uint64) int {
	offset -= sovGrowth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegionMetric) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = m.TaxIndex.Size()
	n += 1 + l + sovGrowth(uint64(l))
	l = m.GdpIndex.Size()
	n += 1 + l + sovGrowth(uint64(l))
	l = m.ExportsIndex.Size()
	n += 1 + l + sovGrowth(uint64(l))
	return n
}

func (m *GrowthScore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = m.Score.Size()
	n += 1 + l + sovGrowth(uint64(l))
	l = m.DelegationMultiplier.Size()
	n += 1 + l + sovGrowth(uint64(l))
	l = m.PayrollMultiplier.Size()
	n += 1 + l + sovGrowth(uint64(l))
	return n
}

func (m *Occupation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = m.Occupation.Size()
	n += 1 + l + sovGrowth(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CurrentPeriod)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = len(m.Oracle)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	l = len(m.NationalRegionId)
	if l > 0 {
		n += 1 + l + sovGrowth(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGrowth(uint64(l))
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovGrowth(uint64(l))
		}
	}
	if len(m.Scores) > 0 {
		for _, e := range m.Scores {
			l = e.Size()
			n += 1 + l + sovGrowth(uint64(l))
		}
	}
	if len(m.OccupationList) > 0 {
		for _, e := range m.OccupationList {
			l = e.Size()
			n += 1 + l + sovGrowth(uint64(l))
		}
	}
	return n
}

func sovGrowth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGrowth(x uint64) (n int) {
	return sovGrowth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegionMetric) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegionMetric: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegionMetric: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GdpIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GdpIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExportsIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExportsIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGrowth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGrowth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GrowthScore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GrowthScore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GrowthScore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Score.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegationMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayrollMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PayrollMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGrowth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGrowth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Occupation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Occupation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Occupation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Occupation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Occupation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGrowth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGrowth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPeriod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentPeriod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NationalRegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NationalRegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGrowth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGrowth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, RegionMetric{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scores = append(m.Scores, GrowthScore{})
			if err := m.Scores[len(m.Scores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OccupationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGrowth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGrowth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OccupationList = append(m.OccupationList, Occupation{})
			if err := m.OccupationList[len(m.OccupationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGrowth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGrowth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGrowth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGrowth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGrowth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGrowth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGrowth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGrowth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGrowth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGrowth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGrowth = fmt.Errorf("proto: unexpected end of group")
)
