// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/growth/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRegionMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRegionMetricRequest) Reset() {
	*x = QueryRegionMetricRequest{}
	mi := &file_uagd_growth_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRegionMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRegionMetricRequest) ProtoMessage() {}

func (x *QueryRegionMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRegionMetricRequest.ProtoReflect.Descriptor instead.
func (*QueryRegionMetricRequest) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRegionMetricRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *QueryRegionMetricRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type QueryRegionMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *RegionMetric          `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRegionMetricResponse) Reset() {
	*x = QueryRegionMetricResponse{}
	mi := &file_uagd_growth_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRegionMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRegionMetricResponse) ProtoMessage() {}

func (x *QueryRegionMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRegionMetricResponse.ProtoReflect.Descriptor instead.
func (*QueryRegionMetricResponse) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRegionMetricResponse) GetMetric() *RegionMetric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type QueryGrowthScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGrowthScoreRequest) Reset() {
	*x = QueryGrowthScoreRequest{}
	mi := &file_uagd_growth_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGrowthScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGrowthScoreRequest) ProtoMessage() {}

func (x *QueryGrowthScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGrowthScoreRequest.ProtoReflect.Descriptor instead.
func (*QueryGrowthScoreRequest) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryGrowthScoreRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *QueryGrowthScoreRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type QueryGrowthScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *GrowthScore           `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGrowthScoreResponse) Reset() {
	*x = QueryGrowthScoreResponse{}
	mi := &file_uagd_growth_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGrowthScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGrowthScoreResponse) ProtoMessage() {}

func (x *QueryGrowthScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGrowthScoreResponse.ProtoReflect.Descriptor instead.
func (*QueryGrowthScoreResponse) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGrowthScoreResponse) GetScore() *GrowthScore {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_uagd_growth_v1_query_proto protoreflect.FileDescriptor

const file_uagd_growth_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1auagd/growth/v1/query.proto\x12\x0euagd.growth.v1\x1a\x1buagd/growth/v1/growth.proto\"O\n" +
	"\x18QueryRegionMetricRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"Q\n" +
	"\x19QueryRegionMetricResponse\x124\n" +
	"\x06metric\x18\x01 \x01(\v2\x1c.uagd.growth.v1.RegionMetricR\x06metric\"N\n" +
	"\x17QueryGrowthScoreRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"M\n" +
	"\x18QueryGrowthScoreResponse\x121\n" +
	"\x05score\x18\x01 \x01(\v2\x1b.uagd.growth.v1.GrowthScoreR\x05score2\xce\x01\n" +
	"\x05Query\x12c\n" +
	"\fRegionMetric\x12(.uagd.growth.v1.QueryRegionMetricRequest\x1a).uagd.growth.v1.QueryRegionMetricResponse\x12`\n" +
	"\vGrowthScore\x12'.uagd.growth.v1.QueryGrowthScoreRequest\x1a(.uagd.growth.v1.QueryGrowthScoreResponseB\x15Z\x13uagd/x/growth/typesb\x06proto3"

var (
	file_uagd_growth_v1_query_proto_rawDescOnce sync.Once
	file_uagd_growth_v1_query_proto_rawDescData []byte
)

func file_uagd_growth_v1_query_proto_rawDescGZIP() []byte {
	file_uagd_growth_v1_query_proto_rawDescOnce.Do(func() {
		file_uagd_growth_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_growth_v1_query_proto_rawDesc), len(file_uagd_growth_v1_query_proto_rawDesc)))
	})
	return file_uagd_growth_v1_query_proto_rawDescData
}

var file_uagd_growth_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_uagd_growth_v1_query_proto_goTypes = []any{
	(*QueryRegionMetricRequest)(nil),  // 0: uagd.growth.v1.QueryRegionMetricRequest
	(*QueryRegionMetricResponse)(nil), // 1: uagd.growth.v1.QueryRegionMetricResponse
	(*QueryGrowthScoreRequest)(nil),   // 2: uagd.growth.v1.QueryGrowthScoreRequest
	(*QueryGrowthScoreResponse)(nil),  // 3: uagd.growth.v1.QueryGrowthScoreResponse
	(*RegionMetric)(nil),              // 4: uagd.growth.v1.RegionMetric
	(*GrowthScore)(nil),               // 5: uagd.growth.v1.GrowthScore
}
var file_uagd_growth_v1_query_proto_depIdxs = []int32{
	4, // 0: uagd.growth.v1.QueryRegionMetricResponse.metric:type_name -> uagd.growth.v1.RegionMetric
	5, // 1: uagd.growth.v1.QueryGrowthScoreResponse.score:type_name -> uagd.growth.v1.GrowthScore
	0, // 2: uagd.growth.v1.Query.RegionMetric:input_type -> uagd.growth.v1.QueryRegionMetricRequest
	2, // 3: uagd.growth.v1.Query.GrowthScore:input_type -> uagd.growth.v1.QueryGrowthScoreRequest
	1, // 4: uagd.growth.v1.Query.RegionMetric:output_type -> uagd.growth.v1.QueryRegionMetricResponse
	3, // 5: uagd.growth.v1.Query.GrowthScore:output_type -> uagd.growth.v1.QueryGrowthScoreResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_uagd_growth_v1_query_proto_init() }
func file_uagd_growth_v1_query_proto_init() {
	if File_uagd_growth_v1_query_proto != nil {
		return
	}
	file_uagd_growth_v1_growth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_growth_v1_query_proto_rawDesc), len(file_uagd_growth_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uagd_growth_v1_query_proto_goTypes,
		DependencyIndexes: file_uagd_growth_v1_query_proto_depIdxs,
		MessageInfos:      file_uagd_growth_v1_query_proto_msgTypes,
	}.Build()
	File_uagd_growth_v1_query_proto = out.File
	file_uagd_growth_v1_query_proto_goTypes = nil
	file_uagd_growth_v1_query_proto_depIdxs = nil
}
