// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: uagd/growth/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgSetRegionMetric allows the oracle authority to set regional metrics for a period.
type MsgSetRegionMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	RegionId      string                 `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	TaxIndex      string                 `protobuf:"bytes,4,opt,name=tax_index,json=taxIndex,proto3" json:"tax_index,omitempty"`
	GdpIndex      string                 `protobuf:"bytes,5,opt,name=gdp_index,json=gdpIndex,proto3" json:"gdp_index,omitempty"`
	ExportsIndex  string                 `protobuf:"bytes,6,opt,name=exports_index,json=exportsIndex,proto3" json:"exports_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetRegionMetric) Reset() {
	*x = MsgSetRegionMetric{}
	mi := &file_uagd_growth_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetRegionMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetRegionMetric) ProtoMessage() {}

func (x *MsgSetRegionMetric) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetRegionMetric.ProtoReflect.Descriptor instead.
func (*MsgSetRegionMetric) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSetRegionMetric) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgSetRegionMetric) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *MsgSetRegionMetric) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *MsgSetRegionMetric) GetTaxIndex() string {
	if x != nil {
		return x.TaxIndex
	}
	return ""
}

func (x *MsgSetRegionMetric) GetGdpIndex() string {
	if x != nil {
		return x.GdpIndex
	}
	return ""
}

func (x *MsgSetRegionMetric) GetExportsIndex() string {
	if x != nil {
		return x.ExportsIndex
	}
	return ""
}

type MsgSetRegionMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *GrowthScore           `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetRegionMetricResponse) Reset() {
	*x = MsgSetRegionMetricResponse{}
	mi := &file_uagd_growth_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetRegionMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetRegionMetricResponse) ProtoMessage() {}

func (x *MsgSetRegionMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uagd_growth_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetRegionMetricResponse.ProtoReflect.Descriptor instead.
func (*MsgSetRegionMetricResponse) Descriptor() ([]byte, []int) {
	return file_uagd_growth_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSetRegionMetricResponse) GetScore() *GrowthScore {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_uagd_growth_v1_tx_proto protoreflect.FileDescriptor

const file_uagd_growth_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x17uagd/growth/v1/tx.proto\x12\x0euagd.growth.v1\x1a\x11amino/amino.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1buagd/growth/v1/growth.proto\"\xcf\x03\n" +
	"\x12MsgSetRegionMetric\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\tR\bregionId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12Y\n" +
	"\ttax_index\x18\x04 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecҴ-\n" +
	"cosmos.DecR\btaxIndex\x12Y\n" +
	"\tgdp_index\x18\x05 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecҴ-\n" +
	"cosmos.DecR\bgdpIndex\x12a\n" +
	"\rexports_index\x18\x06 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecҴ-\n" +
	"cosmos.DecR\fexportsIndex:3\x82\xe7\xb0*\tauthority\x8a\xe7\xb0* uagd/x/growth/MsgSetRegionMetric\"U\n" +
	"\x1aMsgSetRegionMetricResponse\x127\n" +
	"\x05score\x18\x01 \x01(\v2\x1b.uagd.growth.v1.GrowthScoreB\x04\xc8\xde\x1f\x00R\x05score2o\n" +
	"\x03Msg\x12a\n" +
	"\x0fSetRegionMetric\x12\".uagd.growth.v1.MsgSetRegionMetric\x1a*.uagd.growth.v1.MsgSetRegionMetricResponse\x1a\x05\x80\xe7\xb0*\x01B\x15Z\x13uagd/x/growth/typesb\x06proto3"

var (
	file_uagd_growth_v1_tx_proto_rawDescOnce sync.Once
	file_uagd_growth_v1_tx_proto_rawDescData []byte
)

func file_uagd_growth_v1_tx_proto_rawDescGZIP() []byte {
	file_uagd_growth_v1_tx_proto_rawDescOnce.Do(func() {
		file_uagd_growth_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uagd_growth_v1_tx_proto_rawDesc), len(file_uagd_growth_v1_tx_proto_rawDesc)))
	})
	return file_uagd_growth_v1_tx_proto_rawDescData
}

var file_uagd_growth_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uagd_growth_v1_tx_proto_goTypes = []any{
	(*MsgSetRegionMetric)(nil),         // 0: uagd.growth.v1.MsgSetRegionMetric
	(*MsgSetRegionMetricResponse)(nil), // 1: uagd.growth.v1.MsgSetRegionMetricResponse
	(*GrowthScore)(nil),                // 2: uagd.growth.v1.GrowthScore
}
var file_uagd_growth_v1_tx_proto_depIdxs = []int32{
	2, // 0: uagd.growth.v1.MsgSetRegionMetricResponse.score:type_name -> uagd.growth.v1.GrowthScore
	0, // 1: uagd.growth.v1.Msg.SetRegionMetric:input_type -> uagd.growth.v1.MsgSetRegionMetric
	1, // 2: uagd.growth.v1.Msg.SetRegionMetric:output_type -> uagd.growth.v1.MsgSetRegionMetricResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_uagd_growth_v1_tx_proto_init() }
func file_uagd_growth_v1_tx_proto_init() {
	if File_uagd_growth_v1_tx_proto != nil {
		return
	}
	file_uagd_growth_v1_growth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uagd_growth_v1_tx_proto_rawDesc), len(file_uagd_growth_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uagd_growth_v1_tx_proto_goTypes,
		DependencyIndexes: file_uagd_growth_v1_tx_proto_depIdxs,
		MessageInfos:      file_uagd_growth_v1_tx_proto_msgTypes,
	}.Build()
	File_uagd_growth_v1_tx_proto = out.File
	file_uagd_growth_v1_tx_proto_goTypes = nil
	file_uagd_growth_v1_tx_proto_depIdxs = nil
}
