// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uag/growth/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetRegionMetric allows the oracle authority to set regional metrics for a period.
type MsgSetRegionMetric struct {
	Authority    string                      `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	RegionId     string                      `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Period       string                      `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	TaxIndex     cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=tax_index,json=taxIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"tax_index"`
	GdpIndex     cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=gdp_index,json=gdpIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"gdp_index"`
	ExportsIndex cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=exports_index,json=exportsIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"exports_index"`
}

func (m *MsgSetRegionMetric) Reset()         { *m = MsgSetRegionMetric{} }
func (m *MsgSetRegionMetric) String() string { return proto.CompactTextString(m) }
func (*MsgSetRegionMetric) ProtoMessage()    {}
func (*MsgSetRegionMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_260255cc81f0e95f, []int{0}
}
func (m *MsgSetRegionMetric) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRegionMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRegionMetric.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRegionMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRegionMetric.Merge(m, src)
}
func (m *MsgSetRegionMetric) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRegionMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRegionMetric.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRegionMetric proto.InternalMessageInfo

func (m *MsgSetRegionMetric) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetRegionMetric) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *MsgSetRegionMetric) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

type MsgSetRegionMetricResponse struct {
	Score GrowthScore `protobuf:"bytes,1,opt,name=score,proto3" json:"score"`
}

func (m *MsgSetRegionMetricResponse) Reset()         { *m = MsgSetRegionMetricResponse{} }
func (m *MsgSetRegionMetricResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetRegionMetricResponse) ProtoMessage()    {}
func (*MsgSetRegionMetricResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_260255cc81f0e95f, []int{1}
}
func (m *MsgSetRegionMetricResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRegionMetricResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRegionMetricResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRegionMetricResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRegionMetricResponse.Merge(m, src)
}
func (m *MsgSetRegionMetricResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRegionMetricResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRegionMetricResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRegionMetricResponse proto.InternalMessageInfo

func (m *MsgSetRegionMetricResponse) GetScore() GrowthScore {
	if m != nil {
		return m.Score
	}
	return GrowthScore{}
}

func init() {
	proto.RegisterType((*MsgSetRegionMetric)(nil), "uag.growth.v1.MsgSetRegionMetric")
	proto.RegisterType((*MsgSetRegionMetricResponse)(nil), "uag.growth.v1.MsgSetRegionMetricResponse")
}

func init() { proto.RegisterFile("uag/growth/v1/tx.proto", fileDescriptor_260255cc81f0e95f) }

var fileDescriptor_260255cc81f0e95f = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x77, 0x4d, 0x13, 0xba, 0xa3, 0x45, 0x1c, 0x4a, 0x5d, 0xb7, 0xb0, 0xd1, 0x9e, 0x34,
	0xd8, 0x5d, 0x12, 0xa1, 0x07, 0x6f, 0x86, 0x82, 0x14, 0x8c, 0x87, 0x8d, 0x78, 0xf0, 0xb2, 0x8c,
	0x3b, 0xc3, 0x64, 0x90, 0xdd, 0x59, 0x66, 0x26, 0x75, 0x73, 0x13, 0x8f, 0x9e, 0xfc, 0x47, 0x84,
	0x1c, 0xfa, 0x47, 0xf4, 0x58, 0x7a, 0x12, 0x0f, 0x45, 0x92, 0x43, 0xfe, 0x0d, 0x99, 0x1f, 0xa5,
	0xa4, 0x39, 0x08, 0xbd, 0x2c, 0xf3, 0xde, 0xfb, 0xce, 0xe7, 0xfb, 0x76, 0xde, 0x03, 0x7b, 0x53,
	0x44, 0x53, 0x2a, 0xf8, 0x57, 0x35, 0x49, 0x4f, 0xfb, 0xa9, 0x6a, 0x92, 0x5a, 0x70, 0xc5, 0xe1,
	0xce, 0x14, 0xd1, 0xc4, 0xe6, 0x93, 0xd3, 0x7e, 0xf4, 0x08, 0x95, 0xac, 0xe2, 0xa9, 0xf9, 0x5a,
	0x45, 0xf4, 0xb8, 0xe0, 0xb2, 0xe4, 0x32, 0x2d, 0x25, 0xd5, 0x37, 0x4b, 0x49, 0x5d, 0xe1, 0x89,
	0x2d, 0xe4, 0x26, 0x4a, 0x6d, 0xe0, 0x4a, 0xbb, 0x94, 0x53, 0x6e, 0xf3, 0xfa, 0xe4, 0xb2, 0xd1,
	0x7a, 0x0f, 0xce, 0xd5, 0xd4, 0x0e, 0x7e, 0xb5, 0x00, 0x1c, 0x49, 0x3a, 0x26, 0x2a, 0x23, 0x94,
	0xf1, 0x6a, 0x44, 0x94, 0x60, 0x05, 0x3c, 0x02, 0x01, 0x9a, 0xaa, 0x09, 0x17, 0x4c, 0xcd, 0x42,
	0xff, 0xa9, 0xff, 0x3c, 0x18, 0x86, 0x97, 0x67, 0x87, 0xbb, 0xce, 0xed, 0x0d, 0xc6, 0x82, 0x48,
	0x39, 0x56, 0x82, 0x55, 0x34, 0xbb, 0x91, 0xc2, 0x7d, 0x10, 0x08, 0xc3, 0xc9, 0x19, 0x0e, 0xef,
	0xe9, 0x7b, 0xd9, 0xb6, 0x4d, 0x9c, 0x60, 0xb8, 0x07, 0x3a, 0x35, 0x11, 0x8c, 0xe3, 0xb0, 0x65,
	0x2a, 0x2e, 0x82, 0xef, 0x41, 0xa0, 0x50, 0x93, 0xb3, 0x0a, 0x93, 0x26, 0xdc, 0x32, 0x66, 0xfd,
	0xf3, 0xab, 0xae, 0xf7, 0xe7, 0xaa, 0xbb, 0x6f, 0x0d, 0x25, 0xfe, 0x92, 0x30, 0x9e, 0x96, 0x48,
	0x4d, 0x92, 0x77, 0x84, 0xa2, 0x62, 0x76, 0x4c, 0x8a, 0xcb, 0xb3, 0x43, 0xe0, 0xfa, 0x39, 0x26,
	0x45, 0xb6, 0xad, 0x50, 0x73, 0xa2, 0x11, 0x9a, 0x47, 0x71, 0xed, 0x78, 0xed, 0x3b, 0xf3, 0x28,
	0xae, 0x2d, 0xef, 0x23, 0xd8, 0x21, 0x4d, 0xcd, 0x85, 0x92, 0x8e, 0xd9, 0xb9, 0x2b, 0xf3, 0x81,
	0xe3, 0x18, 0xee, 0xeb, 0xc1, 0xf7, 0xd5, 0xbc, 0x77, 0xf3, 0x78, 0x3f, 0x56, 0xf3, 0x5e, 0x57,
	0x8f, 0xaa, 0xb9, 0x1e, 0xd6, 0xe6, 0x60, 0x0e, 0x3e, 0x80, 0x68, 0x33, 0x9b, 0x11, 0x59, 0xf3,
	0x4a, 0x12, 0x78, 0x04, 0xda, 0xb2, 0xe0, 0x82, 0x98, 0x91, 0xdd, 0x1f, 0x44, 0xc9, 0xda, 0x96,
	0x25, 0x6f, 0xcd, 0x69, 0xac, 0x15, 0xc3, 0x2d, 0xdd, 0x7d, 0x66, 0xe5, 0x83, 0x12, 0xb4, 0x46,
	0x92, 0xc2, 0x1c, 0x3c, 0xbc, 0xbd, 0x08, 0xcf, 0x6e, 0x21, 0x36, 0xcd, 0xa3, 0x17, 0xff, 0x95,
	0x5c, 0xf7, 0x17, 0xb5, 0xbf, 0xad, 0xe6, 0x3d, 0x7f, 0xf8, 0xf2, 0x7c, 0x11, 0xfb, 0x17, 0x8b,
	0xd8, 0xff, 0xbb, 0x88, 0xfd, 0x9f, 0xcb, 0xd8, 0xbb, 0x58, 0xc6, 0xde, 0xef, 0x65, 0xec, 0x7d,
	0x82, 0x6b, 0xff, 0xaf, 0x66, 0x35, 0x91, 0x9f, 0x3b, 0x66, 0x53, 0x5f, 0xfd, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xb7, 0xda, 0xa1, 0x2f, 0x4b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetRegionMetric(ctx context.Context, in *MsgSetRegionMetric, opts ...grpc.CallOption) (*MsgSetRegionMetricResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetRegionMetric(ctx context.Context, in *MsgSetRegionMetric, opts ...grpc.CallOption) (*MsgSetRegionMetricResponse, error) {
	out := new(MsgSetRegionMetricResponse)
	err := c.cc.Invoke(ctx, "/uag.growth.v1.Msg/SetRegionMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetRegionMetric(context.Context, *MsgSetRegionMetric) (*MsgSetRegionMetricResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetRegionMetric(ctx context.Context, req *MsgSetRegionMetric) (*MsgSetRegionMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRegionMetric not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetRegionMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetRegionMetric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetRegionMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uag.growth.v1.Msg/SetRegionMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetRegionMetric(ctx, req.(*MsgSetRegionMetric))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uag.growth.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRegionMetric",
			Handler:    _Msg_SetRegionMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uag/growth/v1/tx.proto",
}

func (m *MsgSetRegionMetric) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRegionMetric) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRegionMetric) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExportsIndex.Size()
		i -= size
		if _, err := m.ExportsIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.GdpIndex.Size()
		i -= size
		if _, err := m.GdpIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.TaxIndex.Size()
		i -= size
		if _, err := m.TaxIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetRegionMetricResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRegionMetricResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRegionMetricResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Score.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetRegionMetric) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TaxIndex.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.GdpIndex.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.ExportsIndex.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSetRegionMetricResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Score.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetRegionMetric) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRegionMetric: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRegionMetric: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GdpIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GdpIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExportsIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExportsIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetRegionMetricResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRegionMetricResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRegionMetricResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Score.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
